import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { RequireSession, routeForRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function AccountProfile() { return <RequireSession><ProfileContent /></RequireSession>; }
function ProfileContent() { const { session, logout } = usePhaseSession(); const profile = trpc.phase1.profile.useQuery({ sessionToken: session!.token }); if (profile.isLoading) return <LoadingCare />; const account = profile.data; if (!account) return null; const signOut = async () => { await logout(); router.replace("/login" as never); }; const role = account.role === "super_admin" ? "Maamulaha Sare" : account.role === "store_admin" ? "Maamulaha Dukaan" : "Macmiil"; return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title="Qoraalkayga" back={() => router.replace(routeForRole(account.role) as never)} /><Card style={styles.top}><View style={styles.avatar}><MaterialIcons name="person" size={31} color={palette.purple} /></View><Text style={styles.name}>{account.fullName}</Text><Text style={styles.role}>{role}</Text></Card><Card style={styles.info}><Row label="Email" value={account.email} /><Row label="Taleefan" value={account.phoneNumber} />{account.storeName ? <Row label="Dukaan" value={account.storeName} /> : null}{account.location ? <Row label="Goob" value={account.location} /> : null}{account.username ? <Row label="Magaca isticmaalaha" value={account.username} /> : null}</Card><SecondaryButton label="Settings iyo amniga" icon="settings" onPress={() => router.push("/settings" as never)} /><PrimaryButton label="Ka bax" icon="logout" onPress={signOut} /></ScrollView></Page>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, top: { alignItems: "center", gap: 6, backgroundColor: palette.lavender }, avatar: { height: 64, width: 64, borderRadius: 22, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, name: { color: palette.ink, fontSize: 20, fontWeight: "900" }, role: { color: palette.purple, fontSize: 12, fontWeight: "900" }, info: { gap: 13 }, row: { borderBottomWidth: 1, borderBottomColor: palette.line, paddingBottom: 10 }, label: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, value: { color: palette.ink, fontSize: 14, fontWeight: "800", marginTop: 4 } });
