import { router } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Header, Page, palette, PrimaryButton } from "@/components/iftiin-ui";
import { RequireSession, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function ChangePasswordScreen() { return <RequireSession><ChangePasswordContent /></RequireSession>; }
function ChangePasswordContent() { const { session } = usePhaseSession(); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const change = trpc.phase1.changePassword.useMutation(); async function submit() { setError(""); setSuccess(""); if (newPassword !== confirmPassword) { setError("Labada password cusub isma laha."); return; } try { await change.mutateAsync({ sessionToken: session!.token, currentPassword, newPassword }); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setSuccess("Furaha sirta ah si ammaan ah ayaa loo beddelay."); } catch (issue) { setError(issue instanceof Error ? issue.message : "Password-ka lama beddeli karo."); } } return <Page><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Header title="Beddel furaha sirta ah" subtitle="Ilaali amniga akoonkaaga" back={() => router.back()} /><Card style={styles.note}><Text style={styles.noteTitle}>Talo amni</Text><Text style={styles.noteText}>Dooro password cusub oo ugu yaraan 8 xaraf ah. Ha la wadaagin cid kale.</Text></Card><Card style={styles.form}><Field label="Furaha sirta ah ee hadda jira" value={currentPassword} onChangeText={setCurrentPassword} /><Field label="Furaha sirta ah ee cusub" value={newPassword} onChangeText={setNewPassword} /><Field label="Xaqiiji furaha sirta ah ee cusub" value={confirmPassword} onChangeText={setConfirmPassword} />{error ? <Text style={styles.error}>{error}</Text> : null}{success ? <Text style={styles.success}>{success}</Text> : null}<PrimaryButton label={change.isPending ? "Waa la beddelayaa..." : "Beddel password-ka"} onPress={submit} disabled={!currentPassword || !newPassword || !confirmPassword || change.isPending} /></Card></ScrollView></Page>; }
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} secureTextEntry style={styles.input} placeholderTextColor="#918FA0" /></View>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, note: { backgroundColor: palette.blue, gap: 4 }, noteTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, noteText: { color: palette.muted, fontSize: 12, lineHeight: 18 }, form: { gap: 12 }, field: { gap: 6 }, label: { color: palette.ink, fontSize: 12, fontWeight: "800" }, input: { height: 50, borderRadius: 14, borderColor: palette.line, borderWidth: 1, paddingHorizontal: 13, color: palette.ink }, error: { color: "#A5264B", fontSize: 12, lineHeight: 17 }, success: { color: palette.success, fontSize: 12, fontWeight: "800", lineHeight: 17 } });
