import { router } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Header, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { trpc } from "@/lib/trpc";
import { somaliFormError } from "@/lib/form-errors";

type Form = { fullName: string; storeName: string; phoneNumber: string; email: string; username: string; password: string; confirmPassword: string; location: string };
const blank: Form = { fullName: "", storeName: "", phoneNumber: "", email: "", username: "", password: "", confirmPassword: "", location: "" };
export default function CreateStoreAccount() { const [form, setForm] = useState<Form>(blank); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const register = trpc.phase1.registerStore.useMutation(); const set = (key: keyof Form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); async function submit() { setError(""); setNotice(""); if (form.password !== form.confirmPassword) { setError("Labada furaha sirta ahi isma laha."); return; } try { const result = await register.mutateAsync({ fullName: form.fullName, storeName: form.storeName, phoneNumber: form.phoneNumber, email: form.email, username: form.username, password: form.password, location: form.location }); setNotice(result.message); } catch (issue) { setError(somaliFormError(issue, "Codsiga lama gudbin karo.")); } } return <Page><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Header title="Abuur akoon dukaan" back={() => router.back()} /><Text style={styles.copy}>Dhammee xogtan. Dukaankaagu wuxuu ahaanayaa sugitaan ilaa Maamulaha Sare ansixiyo.</Text><Card style={styles.form}><Input label="Magaca oo buuxa" value={form.fullName} onChangeText={set("fullName")} /><Input label="Magaca dukaanka" value={form.storeName} onChangeText={set("storeName")} /><Input label="Lambarka taleefanka" value={form.phoneNumber} onChangeText={set("phoneNumber")} keyboardType="phone-pad" /><Input label="Email" value={form.email} onChangeText={set("email")} autoCapitalize="none" keyboardType="email-address" /><Input label="Magaca isticmaalaha" value={form.username} onChangeText={set("username")} autoCapitalize="none" hint="Isticmaal xarfo, tirooyin, dhibic (.) ama underscore (_) oo keliya." /><Input label="Furaha sirta ah" value={form.password} onChangeText={set("password")} secureTextEntry /><Input label="Xaqiiji furaha sirta ah" value={form.confirmPassword} onChangeText={set("confirmPassword")} secureTextEntry /><Input label="Goobta" value={form.location} onChangeText={set("location")} />{error ? <Text style={styles.error}>{error}</Text> : null}{notice ? <Text style={styles.notice}>{notice}</Text> : null}<PrimaryButton label={register.isPending ? "Waa la gudbinayaa..." : "Gudbi codsiga dukaanka"} onPress={submit} disabled={Object.values(form).some((value) => !value) || register.isPending} /><SecondaryButton label="Ku noqo gelitaanka" onPress={() => router.replace("/login" as never)} /></Card></ScrollView></Page>; }
function Input({ label, hint, ...props }: { label: string; hint?: string; value: string; onChangeText: (text: string) => void; secureTextEntry?: boolean; autoCapitalize?: "none"; keyboardType?: "phone-pad" | "email-address" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#918FA0" />{hint ? <Text style={styles.hint}>{hint}</Text> : null}</View>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 32 }, copy: { color: palette.muted, lineHeight: 20, fontSize: 13 }, form: { gap: 11 }, field: { gap: 6 }, label: { color: palette.ink, fontSize: 12, fontWeight: "800" }, input: { borderWidth: 1, borderColor: palette.line, borderRadius: 14, paddingHorizontal: 13, height: 49, color: palette.ink }, hint: { color: palette.muted, fontSize: 10, lineHeight: 14 }, error: { color: "#A5264B", fontSize: 12, lineHeight: 18 }, notice: { color: palette.success, lineHeight: 18, fontSize: 12, fontWeight: "800" } });
