import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { getApiBaseUrl } from "@/constants/oauth";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";
const categories = ["Dhammaan", "Cleanser", "Moisturizer", "Serum", "Sunscreen", "Treatment", "Kale"];
export default function CustomerStore() { return <RequireRole role="customer"><StoreProducts /></RequireRole>; }
function StoreProducts() { const { session } = usePhaseSession(); const { storeId, storeName } = useLocalSearchParams<{ storeId: string; storeName?: string }>(); const [search, setSearch] = useState(""); const [category, setCategory] = useState("Dhammaan"); const products = trpc.phase1.customerProducts.useQuery({ sessionToken: session!.token, storeAdminId: Number(storeId), search: search || undefined, category: category === "Dhammaan" ? undefined : category }, { enabled: Boolean(storeId) }); if (products.isLoading) return <LoadingCare />; return <Page noPadding><FlatList data={products.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title={storeName || "Dukaan"} subtitle="Alaabta la heli karo" back={() => router.back()} /><View style={styles.search}><MaterialIcons name="search" size={20} color={palette.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Raadi product ama brand" placeholderTextColor="#918FA0" style={styles.input} /></View><FlatList horizontal data={categories} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({ item }) => <Pressable onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipOn]}><Text style={[styles.chipText, category === item && styles.chipTextOn]}>{item}</Text></Pressable>} /></View>} ListEmptyComponent={<EmptyState icon="inventory-2" title="Product lama helin" detail="Dukaankan hadda product la heli karo ma laha." />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/product-details" as never, params: { productId: String(item.id) } })}><Card style={styles.product}><View style={styles.image}>{item.imageUrl ? <Image source={{ uri: `${getApiBaseUrl()}${item.imageUrl}` }} style={styles.imageFill} /> : <MaterialIcons name="inventory-2" size={24} color={palette.purple} />}</View><View style={{ flex: 1 }}><Text style={styles.category}>{item.category}</Text><Text style={styles.name}>{item.name}</Text><Text style={styles.brand}>{item.brand}</Text><View style={styles.priceRow}><Text style={styles.price}>${item.finalPrice}</Text>{item.discountType !== "none" ? <Text style={styles.old}>${item.originalPrice}</Text> : null}</View><Text style={styles.stock}>{item.stock > 0 ? "Waa la helayaa" : "Hadda lama heli karo"}</Text></View><MaterialIcons name="chevron-right" size={22} color={palette.purple} /></Card></Pressable>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20, gap: 10 }, search: { height: 50, borderWidth: 1, borderColor: palette.line, borderRadius: 15, flexDirection: "row", alignItems: "center", paddingHorizontal: 13, gap: 8 }, input: { flex: 1, color: palette.ink }, chips: { gap: 8, paddingRight: 20 }, chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: palette.line, backgroundColor: "#F8F7FC" }, chipOn: { backgroundColor: palette.lavender, borderColor: palette.purple }, chipText: { color: palette.muted, fontSize: 11, fontWeight: "800" }, chipTextOn: { color: palette.purple }, product: { marginHorizontal: 20, padding: 12, flexDirection: "row", alignItems: "center", gap: 11 }, image: { width: 67, height: 67, borderRadius: 17, backgroundColor: palette.lavender, overflow: "hidden", alignItems: "center", justifyContent: "center" }, imageFill: { width: "100%", height: "100%" }, category: { color: palette.purple, fontSize: 9, fontWeight: "900" }, name: { color: palette.ink, fontSize: 14, fontWeight: "900", marginTop: 3 }, brand: { color: palette.muted, fontSize: 11, marginTop: 2 }, priceRow: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 5 }, price: { color: palette.ink, fontSize: 14, fontWeight: "900" }, old: { color: palette.muted, fontSize: 11, textDecorationLine: "line-through" }, stock: { color: palette.muted, fontSize: 10, marginTop: 3 } });
