import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function CustomerStores() { return <RequireRole role="customer"><StoresContent /></RequireRole>; }
function StoresContent() { const { session } = usePhaseSession(); const [search, setSearch] = useState(""); const stores = trpc.phase1.customerStores.useQuery({ sessionToken: session!.token, search: search || undefined }); if (stores.isLoading) return <LoadingCare />; return <Page noPadding><FlatList data={stores.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Dukaamada" subtitle="Dooro dukaan firfircoon" back={() => router.back()} /><View style={styles.search}><MaterialIcons name="search" size={20} color={palette.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Raadi dukaan ama goob" placeholderTextColor="#918FA0" style={styles.input} /></View></View>} ListEmptyComponent={<EmptyState icon="storefront" title="Dukaan lama helin" detail="Hadda wax dukaan firfircoon ah lama helin." />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/customer-store" as never, params: { storeId: String(item.id), storeName: item.storeName } })}><Card style={styles.store}><View style={styles.icon}><MaterialIcons name="storefront" size={25} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.name}>{item.storeName}</Text><Text style={styles.detail}>{item.location || "Goob lama gelin"}</Text><Text style={styles.detail}>{item.phoneNumber}</Text></View><MaterialIcons name="chevron-right" size={23} color={palette.purple} /></Card></Pressable>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20, gap: 12 }, search: { height: 50, borderWidth: 1, borderColor: palette.line, borderRadius: 15, flexDirection: "row", alignItems: "center", paddingHorizontal: 13, gap: 8 }, input: { flex: 1, color: palette.ink }, store: { marginHorizontal: 20, flexDirection: "row", alignItems: "center", gap: 12, padding: 14 }, icon: { width: 49, height: 49, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: palette.lavender }, name: { color: palette.ink, fontSize: 16, fontWeight: "900" }, detail: { color: palette.muted, fontSize: 11, marginTop: 3 } });
