import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function DeliverySettingsScreen() { return <RequireRole role="store_admin"><DeliveryContent /></RequireRole>; }
function DeliveryContent() { const { session } = usePhaseSession(); const settings = trpc.phase1.deliverySettings.useQuery({ sessionToken: session!.token }); const save = trpc.phase1.saveDeliverySettings.useMutation(); const [enabled, setEnabled] = useState(false); const [fee, setFee] = useState("0"); const [areas, setAreas] = useState(""); const [notice, setNotice] = useState(""); useEffect(() => { if (settings.data) { setEnabled(settings.data.deliveryEnabled); setFee(String(settings.data.deliveryFee)); setAreas(settings.data.deliveryAreas ?? ""); } }, [settings.data]); if (settings.isLoading) return <LoadingCare />; async function submit() { setNotice(""); try { await save.mutateAsync({ sessionToken: session!.token, deliveryEnabled: enabled, deliveryFee: Math.max(0, Math.round(Number(fee) || 0)), deliveryAreas: areas }); setNotice("Delivery settings si guul leh ayaa loo kaydiyey."); } catch (issue) { setNotice(issue instanceof Error ? issue.message : "Settings lama kaydin karo."); } } return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title="Delivery settings" subtitle="Dejinta gaarsiinta dukaankaaga" back={() => router.back()} /><Card style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="local-shipping" size={28} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.heroTitle}>Gaarsiinta product-yada</Text><Text style={styles.heroText}>Daar ama dami delivery; geli khidmada iyo meelaha aad gaarsiiso.</Text></View></Card><Card style={styles.form}><View style={styles.switchRow}><View style={{ flex: 1 }}><Text style={styles.label}>Delivery</Text><Text style={styles.help}>{enabled ? "Delivery-ga dukaankaagu waa daaran yahay" : "Delivery-ga dukaankaagu waa damman yahay"}</Text></View><Switch value={enabled} onValueChange={setEnabled} trackColor={{ false: "#D8D4E7", true: "#BEB6FF" }} thumbColor={enabled ? palette.purple : "#FFFFFF"} /></View><View style={styles.field}><Text style={styles.label}>Khidmada delivery-ga</Text><TextInput value={fee} onChangeText={setFee} keyboardType="numeric" style={styles.input} placeholderTextColor="#918FA0" /></View><View style={styles.field}><Text style={styles.label}>Meelaha delivery-ga</Text><TextInput value={areas} onChangeText={setAreas} multiline style={[styles.input, styles.textarea]} placeholder="Tusaale: Hargeisa, Jigjiga, Borama" placeholderTextColor="#918FA0" /></View>{notice ? <Text style={notice.startsWith("Delivery") ? styles.success : styles.error}>{notice}</Text> : null}<PrimaryButton label={save.isPending ? "Waa la kaydinayaa..." : "Kaydi delivery settings"} onPress={submit} disabled={save.isPending} /></Card></ScrollView></Page>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, hero: { flexDirection: "row", gap: 12, alignItems: "center", backgroundColor: palette.lavender }, heroIcon: { height: 52, width: 52, borderRadius: 18, backgroundColor: "#FFFFFF", justifyContent: "center", alignItems: "center" }, heroTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" }, heroText: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, form: { gap: 14 }, switchRow: { flexDirection: "row", alignItems: "center", gap: 10 }, label: { color: palette.ink, fontSize: 12, fontWeight: "900" }, help: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, field: { gap: 6 }, input: { height: 49, borderRadius: 14, borderWidth: 1, borderColor: palette.line, paddingHorizontal: 13, color: palette.ink }, textarea: { minHeight: 90, height: "auto", paddingTop: 12, textAlignVertical: "top" }, success: { color: palette.success, fontSize: 12, fontWeight: "800" }, error: { color: "#A5264B", fontSize: 12, fontWeight: "800" } });
