import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, Header, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { routeForRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function LoginScreen() {
  const { session, loaded, setSession } = usePhaseSession();
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const login = trpc.phase1.login.useMutation();
  useEffect(() => { if (loaded && session) router.replace(routeForRole(session.account.role) as never); }, [loaded, session]);
  async function submit() { setError(""); try { const result = await login.mutateAsync({ identifier: identifier.trim(), password }); await setSession({ token: result.sessionToken, account: result.account }); router.replace(routeForRole(result.account.role) as never); } catch (issue) { setError(issue instanceof Error ? issue.message : "Gelitaanka lama dhammaystiri karo."); } }
  return <Page><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Header title="Iftiin Skin Care" subtitle="Gelitaanka wejiga koowaad" /><View style={styles.hero}><Text style={styles.eyebrow}>WAJIGA 1</Text><Text style={styles.title}>Soo gal akoonkaaga</Text><Text style={styles.copy}>Maamulaha Sare ee gaarka ah, dukaamada ansixintoodu dhammaystiran tahay, iyo macaamiishu halkan ayay ka soo galaan.</Text></View><Card style={styles.form}><Text style={styles.formTitle}>Gelitaan</Text><Field label="Email ama magaca isticmaalaha" value={identifier} onChangeText={setIdentifier} autoCapitalize="none" /><Field label="Furaha sirta ah" value={password} onChangeText={setPassword} secureTextEntry /><Pressable onPress={() => router.push("/forgot-password" as never)}><Text style={styles.forgot}>Furaha sirta ah ma iloowday?</Text></Pressable><Text style={styles.error}>{error}</Text><PrimaryButton label={login.isPending ? "Waa la gelayaa..." : "Soo gal"} onPress={submit} disabled={!identifier || !password || login.isPending} /></Card><Card style={styles.option}><Text style={styles.optionTitle}>Ma leedahay dukaan?</Text><Text style={styles.optionText}>Isdiiwaangeli; codsigaaga wuxuu sugayaa ansixinta Maamulaha Sare.</Text><SecondaryButton label="Abuur akoon dukaan" icon="storefront" onPress={() => router.push("/create-store-account" as never)} /></Card><Card style={styles.option}><Text style={styles.optionTitle}>Ma tahay macmiil?</Text><Text style={styles.optionText}>Samee akoon macmiil oo firfircoon isla markiiba.</Text><SecondaryButton label="Abuur akoon macmiil" icon="person-add" onPress={() => router.push("/create-customer-account" as never)} /></Card>{!loaded ? <ActivityIndicator color={palette.purple} /> : null}</ScrollView></Page>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (text: string) => void; secureTextEntry?: boolean; autoCapitalize?: "none" | "sentences" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#918FA0" /></View>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 32 }, hero: { backgroundColor: palette.lavender, borderRadius: 25, padding: 20, gap: 7 }, eyebrow: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: palette.ink, fontSize: 25, fontWeight: "900" }, copy: { color: palette.muted, fontSize: 13, lineHeight: 20 }, form: { gap: 12 }, formTitle: { color: palette.ink, fontSize: 18, fontWeight: "900" }, field: { gap: 6 }, label: { color: palette.ink, fontSize: 12, fontWeight: "800" }, input: { borderWidth: 1, borderColor: palette.line, borderRadius: 14, paddingHorizontal: 13, height: 50, color: palette.ink, backgroundColor: "#FFFFFF" }, error: { color: "#A5264B", fontSize: 12, lineHeight: 17 }, forgot: { color: palette.purple, fontSize: 12, fontWeight: "800", textAlign: "right" }, option: { gap: 7 }, optionTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" }, optionText: { color: palette.muted, fontSize: 12, lineHeight: 18 } });
