import { router } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";
const labels: Record<string, string> = { pending: "Sugaya lacag-bixin", payment_confirmed: "Lacagta waa la xaqiijiyey", processing: "Hawlgal ayaa socda", ready: "Dalabkaagu waa diyaar", out_for_delivery: "Wuxuu ku jiraa delivery", delivered: "La geeyey", completed: "Waa la dhammaystiray", cancelled: "La joojiyey", confirmed: "La xaqiijiyey (hore)", preparing: "Diyaar garow (hore)" };
export default function MyOrders() { return <RequireRole role="customer"><Orders /></RequireRole>; }
function Orders() { const { session } = usePhaseSession(); const orders = trpc.phase1.customerOrders.useQuery({ sessionToken: session!.token }); const cancel = trpc.phase1.cancelCustomerOrder.useMutation({ onSuccess: () => orders.refetch() }); if (orders.isLoading) return <LoadingCare />; const cancelOrder = (orderId: number) => Alert.alert("Jooji dalabka", "Ma joojinaysaa dalabkan sugaya? Stock-ga product-yada waa lagu soo celinayaa.", [{ text: "Maya", style: "cancel" }, { text: "Haa, jooji", style: "destructive", onPress: () => cancel.mutate({ sessionToken: session!.token, orderId }) }]); const detail = (orderId: number) => router.push({ pathname: "/order-detail" as never, params: { orderId: String(orderId) } }); return <Page noPadding><FlatList data={orders.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Dalabyadayda" subtitle="La soco xaalad kasta oo dukaanku cusboonaysiiyo" back={() => router.back()} /></View>} ListEmptyComponent={<EmptyState icon="receipt-long" title="Dalab ma lihid" detail="Markaad product doorato oo cart-ka gudbiso, dalabkaagu halkan ayuu kasoo muuqanayaa." />} renderItem={({ item }) => <Card style={styles.order}><View style={styles.top}><View><Text style={styles.orderId}>Dalab #{item.id}</Text><Text style={styles.store}>{item.storeName || "Dukaan"}</Text></View><View style={styles.badge}><Text style={styles.badgeText}>{labels[item.status]}</Text></View></View><Text style={styles.items}>{item.items.map((line) => `${line.productName} × ${line.quantity}`).join(" · ")}</Text>{item.payment ? <Text style={styles.payment}>{item.payment.status === "confirmed" ? "Payment: Paid" : `Payment: ${item.payment.status.replaceAll("_", " ")}`}</Text> : null}<View style={styles.bottom}><Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString()}</Text><Text style={styles.total}>{item.total}</Text></View><Pressable onPress={() => detail(item.id)} style={styles.detail}><Text style={styles.detailText}>Eeg faahfaahinta iyo timeline-ka</Text></Pressable>{item.status === "pending" ? <Pressable onPress={() => cancelOrder(item.id)} style={styles.cancel}><Text style={styles.cancelText}>{cancel.isPending ? "Sug..." : "Jooji dalabka"}</Text></Pressable> : null}</Card>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20 }, order: { marginHorizontal: 20, gap: 8 }, top: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, orderId: { color: palette.ink, fontSize: 14, fontWeight: "900" }, store: { color: palette.muted, fontSize: 11, marginTop: 3 }, badge: { backgroundColor: palette.lavender, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 5, alignSelf: "flex-start", maxWidth: 136 }, badgeText: { color: palette.purple, fontSize: 10, fontWeight: "900", textAlign: "right" }, items: { color: palette.muted, fontSize: 11, lineHeight: 17 }, payment: { color: palette.ink, fontSize: 10, fontWeight: "800" }, bottom: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: palette.line, paddingTop: 9 }, date: { color: palette.muted, fontSize: 10 }, total: { color: palette.purple, fontWeight: "900", fontSize: 14 }, detail: { alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: palette.lavender }, detailText: { color: palette.purple, fontSize: 11, fontWeight: "900" }, cancel: { alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: "#FDECEF" }, cancelText: { color: palette.danger, fontSize: 11, fontWeight: "900" } });
