import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireSession, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";
export default function NotificationsScreen() { return <RequireSession><NotificationsContent /></RequireSession>; }
function NotificationsContent() { const { session } = usePhaseSession(); const notices = trpc.phase1.notifications.useQuery({ sessionToken: session!.token }); const read = trpc.phase1.readNotification.useMutation({ onSuccess: () => notices.refetch() }); const readAll = trpc.phase1.readAllNotifications.useMutation({ onSuccess: () => notices.refetch() }); const unreadCount = (notices.data ?? []).filter((notice) => !notice.isRead).length; if (notices.isLoading) return <LoadingCare />; return <Page noPadding><FlatList data={notices.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Ogeysiisyada" subtitle="Wararka dalabyadaada" back={() => router.back()} />{unreadCount ? <Pressable accessibilityRole="button" onPress={() => readAll.mutate({ sessionToken: session!.token })} style={({ pressed }) => [styles.readAll, pressed && { opacity: 0.75 }]}><MaterialIcons name="done-all" size={18} color={palette.purple} /><Text style={styles.readAllText}>{readAll.isPending ? "Sug..." : "Dhammaan akhri"}</Text></Pressable> : null}</View>} ListEmptyComponent={<EmptyState icon="notifications-none" title="Ogeysiin ma jiro" detail="Marka dalab cusub yimaado ama xaaladdiisu is beddesho, halkan ayaad ku arki doontaa." />} renderItem={({ item }) => <Pressable onPress={() => { if (!item.isRead) read.mutate({ sessionToken: session!.token, notificationId: item.id }); }}><Card style={[styles.card, !item.isRead && styles.unread]}><View style={styles.icon}><MaterialIcons name={item.isRead ? "notifications-none" : "notifications"} size={20} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Text style={styles.date}>{new Date(item.createdAt).toLocaleString()}</Text></View>{!item.isRead ? <View style={styles.dot} /> : null}</Card></Pressable>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20 }, readAll: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: palette.lavender, borderRadius: 12, paddingHorizontal: 11, paddingVertical: 9, marginTop: -8, marginBottom: 7 }, readAllText: { color: palette.purple, fontSize: 12, fontWeight: "900" }, card: { marginHorizontal: 20, flexDirection: "row", gap: 11, alignItems: "flex-start" }, unread: { backgroundColor: "#F8F7FF", borderColor: "#CFC9FF" }, icon: { width: 39, height: 39, borderRadius: 14, backgroundColor: palette.lavender, alignItems: "center", justifyContent: "center" }, title: { color: palette.ink, fontSize: 13, fontWeight: "900" }, body: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, date: { color: palette.muted, fontSize: 10, marginTop: 7 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.purple, marginTop: 4 } });
