import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Linking from "expo-linking";
import { router, useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { showAlert } from "@/lib/alert";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { evc_plus: "EVC Plus", edahab: "eDahab", premier_wallet: "Premier Wallet", merchant: "Merchant" };
const statusLabels: Record<string, string> = { pending_payment: "Sugaya lacag-bixin", sent_awaiting_confirmation: "Lacag la diray — sug xaqiijinta dukaanka", confirmed: "Payment Success / Paid", rejected: "Lacag lama xaqiijin", failed: "Lacag-bixin fashilantay" };
const providerUrls: Record<string, string | null> = { edahab: "https://www.edahab.net/", premier_wallet: "https://premierwallets.com/", merchant: null };

export default function OrderPaymentScreen() { return <RequireRole role="customer"><OrderPaymentContent /></RequireRole>; }
function OrderPaymentContent() {
  const { session } = usePhaseSession(); const { orderId: rawOrderId } = useLocalSearchParams<{ orderId: string }>(); const orderId = Number(rawOrderId);
  const detail = trpc.phase1.orderDetail.useQuery({ sessionToken: session!.token, orderId: Number.isInteger(orderId) && orderId > 0 ? orderId : 1 }, { enabled: Number.isInteger(orderId) && orderId > 0, refetchInterval: 8000 });
  const unlockedJourney = trpc.phase1.unlockedSkinJourneyForOrder.useQuery({ sessionToken: session!.token, orderId: Number.isInteger(orderId) && orderId > 0 ? orderId : 1 }, { enabled: detail.data?.payment?.status === "confirmed" });
  const sent = trpc.phase1.markPaymentSent.useMutation({ onSuccess: () => detail.refetch() }); const failed = trpc.phase1.markPaymentFailed.useMutation({ onSuccess: () => detail.refetch() });
  if (detail.isLoading) return <LoadingCare />;
  if (!Number.isInteger(orderId) || !detail.data?.payment || detail.error) return <Page><Header title="Lacag-bixinta" back={() => router.back()} /><EmptyState icon="error-outline" title="Lacag-bixinta lama heli karo" detail="Fadlan ku noqo dalabyadaada oo mar kale isku day." /></Page>;
  const payment = detail.data.payment;
  async function openProvider() { const url = providerUrls[payment.method]; if (!url) { showAlert("Fur app-kaaga lacagta", `Fur app-ka ${labels[payment.method]} ee telefoonkaaga. Lambarka dukaanka laguma soo bandhigayo Iftiin; dukaanku wuxuu xaqiijinayaa lacagta kaddib.`); return; } try { const supported = await Linking.canOpenURL(url); if (supported) await Linking.openURL(url); else showAlert("Fur app-ka lacagta", `Fur app-ka ${labels[payment.method]} ee telefoonkaaga si aad u sii waddo.`); } catch { showAlert("Fur app-ka lacagta", `Fur app-ka ${labels[payment.method]} ee telefoonkaaga si aad u sii waddo.`); } }
  function confirmAndOpenEvc() { showAlert("EVC Plus", `Ma hubtaa inaad bilaabayso dirista lacag dhan ${payment.amount}? Lambarka dukaanka laguma soo bandhigayo Iftiin.`, [{ text: "Maya", style: "cancel" }, { text: "Haa", onPress: () => openEvcUssd() }]); }
  async function openEvcUssd() { try { await Linking.openURL("tel:*770%23"); } catch { showAlert("EVC Plus lama furi karo", "Fur EVC Plus taleefankaaga si aad u sii waddo dirista lacagta."); } }
  function confirmSent() { showAlert("Xaqiiji dirista", "Ma dhab ahaan ayaad lacagta u dirtay akoonka dukaanka? Iftiin ma xaqiijinayo lacagta; dukaanka ayaa akoonkiisa hubinaya.", [{ text: "Maya", style: "cancel" }, { text: "Haa, waan diray", onPress: () => sent.mutate({ sessionToken: session!.token, orderId }) }]); }
  return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title={`Bixi dalab #${orderId}`} subtitle="Lacagta dibadda ku dir; dukaanka ayaa xaqiijinaya" back={() => router.back()} /><Card style={styles.hero}><View style={styles.icon}><MaterialIcons name="account-balance-wallet" size={27} color={palette.purple} /></View><View style={styles.heroCopy}><Text style={styles.method}>{labels[payment.method]}</Text><Text style={styles.status}>{statusLabels[payment.status]}</Text></View></Card><Card style={styles.details}><Text style={styles.label}>HABKA LACAG-BIXINTA</Text><Text style={styles.account}>Xogta akoonka dukaanka waa qarsoon tahay</Text><Text style={styles.label}>LACAGTA SAXDA AH</Text><Text style={styles.amount}>{payment.amount}</Text><Text style={styles.note}>{payment.method === "evc_plus" ? "Marka aad taabato Haa, EVC Plus ayaa si toos ah uga furmaya telefoonkaaga. Iftiin ma muujinayo lambarka dukaanka, mana xaqiijiyo lacagta ilaa dukaanku hubiyo akoonkiisa." : "Ha gelin code xaqiijin Iftiin gudaheeda. Fur habka rasmiga ah ee provider-kaaga; dukaanku ayaa kadib hubinaya helitaanka lacagta."}</Text></Card>{payment.status === "pending_payment" ? <View style={styles.actions}>{payment.method === "evc_plus" ? <PrimaryButton label="Haa — fur EVC Plus" icon="phone-android" onPress={confirmAndOpenEvc} /> : <PrimaryButton label="Fur habka lacag-bixinta" icon="open-in-new" onPress={openProvider} />}<PrimaryButton label={sent.isPending ? "Sug..." : "Waxaan diray lacagta"} icon="check-circle" onPress={confirmSent} disabled={sent.isPending} /><SecondaryButton label={failed.isPending ? "Sug..." : "Lacagta lama diri karin"} icon="error-outline" onPress={() => failed.mutate({ sessionToken: session!.token, orderId })} /></View> : null}{payment.status === "sent_awaiting_confirmation" ? <Card style={styles.wait}><MaterialIcons name="hourglass-top" size={23} color={palette.purple} /><Text style={styles.waitText}>Lacagta waa la diray — sug xaqiijinta dukaanka. Dukaanku wuxuu ka hubinayaa akoonkiisa dhab ah; Iftiin ma sameeyo xaqiijin otomaatig ah.</Text></Card> : null}{payment.status === "confirmed" ? <><Card style={styles.paid}><MaterialIcons name="verified" size={23} color={palette.success} /><Text style={styles.paidText}>Lacag-bixinta waa la xaqiijiyey. Dukaanku hadda wuu sii wadi karaa dalabkaaga.</Text></Card>{unlockedJourney.data ? <PrimaryButton label="Fur Skin Analysis-kaaga" icon="spa" onPress={() => router.replace({ pathname: "/skin-results" as never, params: { journeyId: String(unlockedJourney.data!.id) } })} /> : null}</> : null}<SecondaryButton label="Eeg dalabyadayda" icon="receipt-long" onPress={() => router.replace("/my-orders" as never)} /></ScrollView></Page>;
}
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, hero: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: palette.lavender }, icon: { height: 52, width: 52, borderRadius: 18, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, heroCopy: { flex: 1 }, method: { color: palette.ink, fontSize: 16, fontWeight: "900" }, status: { color: palette.purple, fontSize: 11, fontWeight: "800", marginTop: 4 }, details: { gap: 7 }, label: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 0.8, marginTop: 4 }, account: { color: palette.ink, fontSize: 19, fontWeight: "900" }, amount: { color: palette.purple, fontSize: 27, fontWeight: "900" }, note: { color: palette.muted, fontSize: 11, lineHeight: 17, marginTop: 7 }, actions: { gap: 10 }, wait: { flexDirection: "row", gap: 10, backgroundColor: palette.blue }, waitText: { color: palette.ink, lineHeight: 18, fontSize: 12, flex: 1 }, paid: { flexDirection: "row", gap: 10, backgroundColor: "#EAF8EF" }, paidText: { color: palette.ink, lineHeight: 18, fontSize: 12, flex: 1 } });
