import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton, ProgressLine } from "@/components/iftiin-ui";
import { useCare } from "@/lib/skin-care-context";

const checklist = ["Morning cleanser", "Moisturizer", "Sunscreen", "Night cleanser", "Recommended treatment", "Night moisturizer"];

export default function PlanScreen() {
  const { hydrated, assessment, progress, toggleDailyItem, completeToday } = useCare();
  if (!hydrated) return <LoadingCare />;
  if (!assessment) { router.replace("/(tabs)/scan" as never); return null; }
  const nextDay = Math.min(28, progress.completedDays.length + 1);
  const completion = progress.completedDays.length / 28;
  const ready = checklist.every((item) => progress.dailyItems[item]);
  return <Page><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Header title="Qorshahaaga 28 Maalmood" subtitle="Tallaabooyin deggan, maalintii hal mar" back={() => router.back()} /><View style={styles.hero}><Text style={styles.eyebrow}>DAY {nextDay} / 28</Text><Text style={styles.heroTitle}>Joogteynta yar ayaa muhiim ah.</Text><ProgressLine value={completion * 100} /><Text style={styles.heroSub}>{progress.completedDays.length} maalmood ayaa la dhammeeyay.</Text></View><View style={styles.weekRow}>{[1, 2, 3, 4].map((week) => <View key={week} style={[styles.week, progress.completedDays.length >= week * 7 && styles.weekDone]}><Text style={[styles.weekText, progress.completedDays.length >= week * 7 && { color: "#FFFFFF" }]}>Usbuuca {week}</Text></View>)}</View><Text style={styles.sectionTitle}>Maalinta {nextDay}</Text><Card style={{ gap: 3 }}>{checklist.map((item, index) => <View key={item} style={styles.checkRow}><View style={[styles.timeBadge, index < 3 ? { backgroundColor: palette.blue } : { backgroundColor: palette.lavender }]}><MaterialIcons name={index < 3 ? "wb-sunny" : "dark-mode"} size={16} color={palette.purple} /></View><Text style={styles.checkText}>{item}</Text><View onTouchEnd={() => toggleDailyItem(item)} style={[styles.box, progress.dailyItems[item] && styles.boxDone]}>{progress.dailyItems[item] ? <MaterialIcons name="check" size={16} color="#FFFFFF" /> : null}</View></View>)}</Card><PrimaryButton label={ready ? "Waan dhammeeyay ✓" : "Calaamadee talaabooyinka"} onPress={completeToday} disabled={!ready || progress.completedDays.includes(nextDay)} /><Text style={styles.note}>Progress-kaaga wuxuu ku keydsan yahay qalabkaaga. Waxaad scan cusub samayn kartaa usbuuc kasta si aad u eegto isbeddelka muuqaalka oo keliya.</Text></ScrollView></Page>;
}

const styles = StyleSheet.create({ scroll: { gap: 15, paddingBottom: 30 }, hero: { padding: 20, borderRadius: 25, backgroundColor: palette.lavender, gap: 10 }, eyebrow: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, heroTitle: { color: palette.ink, fontSize: 21, fontWeight: "900" }, heroSub: { color: palette.muted, fontSize: 12 }, weekRow: { flexDirection: "row", gap: 7 }, week: { flex: 1, height: 47, justifyContent: "center", alignItems: "center", backgroundColor: "#F8F7FD", borderRadius: 14, borderWidth: 1, borderColor: palette.line }, weekDone: { backgroundColor: palette.purple, borderColor: palette.purple }, weekText: { color: palette.muted, fontSize: 10, fontWeight: "800" }, sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: "900" }, checkRow: { minHeight: 56, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: "#F0EFF6" }, timeBadge: { width: 33, height: 33, alignItems: "center", justifyContent: "center", borderRadius: 11 }, checkText: { flex: 1, color: palette.ink, fontSize: 13, fontWeight: "700" }, box: { width: 25, height: 25, borderRadius: 8, borderWidth: 1.5, borderColor: "#C7C3DA", justifyContent: "center", alignItems: "center" }, boxDone: { backgroundColor: palette.success, borderColor: palette.success }, note: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 6 } });
