import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, ProgressLine, SecondaryButton } from "@/components/iftiin-ui";
import { SCAN_DAY_SLOTS } from "@/lib/skin-care";
import { useCare } from "@/lib/skin-care-context";

export default function ProgressScreen() {
  const { hydrated, assessment, history, progress } = useCare();
  if (!hydrated) return <LoadingCare />;
  if (!assessment) return <Page><EmptyState icon="insights" title="Progress-kaaga halkan ayuu imanayaa" detail="Samee Skin Scan-kaaga ugu horreeya si aad u bilowdo qorshaha iyo la socodka." action={<PrimaryButton label="Bilow Scan" onPress={() => router.navigate("/(tabs)/scan" as never)} />} /></Page>;

  const latest = history[0] ?? assessment;
  const earlier = history[1];
  const completed = progress.completedDays.length;
  const weeks = [1, 2, 3, 4];
  const savedSlots = new Set(history.map((item) => item.daySlot));

  return <Page><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Header title="Progress" subtitle="Isbeddel yar, joogteyn weyn" back={() => router.back()} /><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="trending-up" size={26} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.eyebrow}>28-DAY PLAN</Text><Text style={styles.heroTitle}>{completed} / 28 maalmood</Text><ProgressLine value={(completed / 28) * 100} /></View></View><Text style={styles.sectionTitle}>Marxaladahaaga</Text><View style={styles.weekGrid}>{weeks.map((week) => { const reached = completed >= week * 7; return <Card key={week} style={[styles.weekCard, reached && styles.weekCardDone]}><MaterialIcons name={reached ? "check-circle" : "radio-button-unchecked"} size={18} color={reached ? palette.success : "#BAB5CF"} /><Text style={styles.weekTitle}>Week {week}</Text><Text style={styles.weekText}>{reached ? "Waa la dhammeeyay" : `${Math.max(1, week * 7 - completed)} maalmood ayaa ka harsan`}</Text></Card>; })}</View><Text style={styles.sectionTitle}>Scan history</Text><Card style={styles.historyCard}><Text style={styles.historyNote}>Qaado scan cusub Day 1, Day 7, Day 14, Day 21, iyo Day 28 si aad u samayso isbarbardhig muuqaal ah.</Text><View style={styles.slotRow}>{SCAN_DAY_SLOTS.map((slot) => <View key={slot} style={[styles.slot, savedSlots.has(slot) && styles.slotSaved]}><MaterialIcons name={savedSlots.has(slot) ? "check" : "add"} size={15} color={savedSlots.has(slot) ? palette.success : palette.purple} /><Text style={[styles.slotText, savedSlots.has(slot) && { color: palette.success }]}>{slot}</Text></View>)}</View></Card><Text style={styles.sectionTitle}>Isbarbardhigga sawirrada</Text><Card style={styles.comparison}><Text style={styles.comparisonNote}>Sawirrada waxaa loo eegayaa isbarbardhig muuqaal ah oo keliya, mana muujiyaan diagnosis ama isbeddel caafimaad.</Text>{earlier ? <View style={styles.photos}><PhotoCell label={earlier.daySlot} uri={earlier.photoUri} /><View style={styles.arrow}><MaterialIcons name="arrow-forward" size={19} color={palette.purple} /></View><PhotoCell label={latest.daySlot} uri={latest.photoUri} /></View> : <View style={styles.noCompare}><MaterialIcons name="photo-library" size={31} color={palette.purple} /><Text style={styles.noCompareTitle}>Sawir labaad ayaa loo baahan yahay</Text><Text style={styles.noCompareText}>Samee scan cusub Day 7 ama marka aad rabto inaad aragto labada sawir dhinac-dhinac.</Text></View>}</Card><PrimaryButton label="Samee Scan Cusub" icon="photo-camera" onPress={() => router.navigate("/(tabs)/scan" as never)} /><SecondaryButton label="Fur Qorshaha 28 Maalmood" icon="calendar-month" onPress={() => router.push("/plan" as never)} /></ScrollView></Page>;
}

function PhotoCell({ label, uri }: { label: string; uri: string }) { return <View style={styles.photoCell}><Image source={{ uri }} style={styles.photo} /><Text style={styles.photoLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({ scroll: { gap: 15, paddingBottom: 30 }, hero: { backgroundColor: palette.lavender, borderRadius: 24, padding: 17, flexDirection: "row", alignItems: "center", gap: 12 }, heroIcon: { height: 48, width: 48, borderRadius: 17, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, eyebrow: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, heroTitle: { color: palette.ink, fontSize: 19, fontWeight: "900", marginVertical: 5 }, sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: "900", marginTop: 5 }, weekGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, weekCard: { width: "47%", padding: 13, gap: 5 }, weekCardDone: { backgroundColor: "#F0FAF3", borderColor: "#B9E7C7" }, weekTitle: { color: palette.ink, fontWeight: "900", fontSize: 13 }, weekText: { color: palette.muted, fontSize: 11, lineHeight: 16 }, historyCard: { gap: 10 }, historyNote: { color: palette.muted, fontSize: 12, lineHeight: 18 }, slotRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, slot: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, paddingVertical: 7, borderRadius: 10, backgroundColor: palette.lavender }, slotSaved: { backgroundColor: "#E5F5EB" }, slotText: { color: palette.purple, fontWeight: "900", fontSize: 10 }, comparison: { gap: 14 }, comparisonNote: { color: palette.muted, fontSize: 12, lineHeight: 18 }, photos: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 7 }, photoCell: { flex: 1, alignItems: "center", gap: 7 }, photo: { width: "100%", height: 150, borderRadius: 15, backgroundColor: palette.blue }, photoLabel: { color: palette.ink, fontSize: 11, fontWeight: "800" }, arrow: { width: 28, height: 28, borderRadius: 14, backgroundColor: palette.lavender, justifyContent: "center", alignItems: "center" }, noCompare: { alignItems: "center", gap: 8, paddingVertical: 16, paddingHorizontal: 15 }, noCompareTitle: { color: palette.ink, fontSize: 15, fontWeight: "900" }, noCompareText: { color: palette.muted, textAlign: "center", fontSize: 12, lineHeight: 18 } });
