import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { showAlert } from "@/lib/alert";

import { Card, Header, Page, palette, SecondaryButton } from "@/components/iftiin-ui";
import { useLanguage } from "@/lib/language-context";
import { RequireSession, routeForRole, usePhaseSession } from "@/lib/phase1-session";

export default function SettingsScreen() { return <RequireSession><SettingsContent /></RequireSession>; }

function SettingsContent() {
  const { session, logout } = usePhaseSession();
  const { language, setLanguage } = useLanguage();
  const account = session!.account;
  const english = language === "en";
  const role = account.role === "super_admin" ? (english ? "Super Admin" : "Maamulaha Sare") : account.role === "store_admin" ? (english ? "Store Admin" : "Maamulaha Dukaan") : (english ? "Customer" : "Macmiil");
  const copy = english ? { title: "Settings", sub: "Manage your account and preferences", account: "ACCOUNT AND SECURITY", password: "Change password", passwordDetail: "Confirm your current password before changing it.", profile: "Profile details", profileDetail: "View your email, phone and account details.", language: "LANGUAGE", choose: "Choose the language you prefer in the main customer experience.", appearance: "APPEARANCE", mono: "White and light blue", monoDetail: "Iftiin uses a clean, calm white and light-blue appearance.", session: "SESSION", logout: "Log out", open: "Open", cancel: "Cancel", leave: "Do you want to log out of this account?", exit: "Log out" } : { title: "Settings", sub: "Maamul akoonkaaga iyo dookhyada", account: "AKOONKA IYO AMNIGA", password: "Beddel furaha sirta ah", passwordDetail: "Hubi password-ka hadda jira ka hor intaadan beddelin.", profile: "Xogta profile-ka", profileDetail: "Eeg email-ka, taleefanka, iyo xogta akoonkaaga.", language: "LUUQADDA", choose: "Dooro luuqadda aad rabto in aad ku isticmaasho qaybaha muhiimka ah ee app-ka.", appearance: "MUUQAALKA", mono: "Cad iyo buluug khafiif ah", monoDetail: "Iftiin hadda wuxuu adeegsadaa muuqaal nadiif ah oo cad iyo buluug khafiif ah.", session: "KALFADHIGA", logout: "Ka bax akoonka", open: "Fur", cancel: "Jooji", leave: "Ma rabtaa inaad ka baxdo akoonkan?", exit: "Ka bax" };
  const signOut = () => showAlert(copy.logout, copy.leave, [{ text: copy.cancel, style: "cancel" }, { text: copy.exit, style: "destructive", onPress: async () => { await logout(); router.replace("/login" as never); } }]);
  return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title={copy.title} subtitle={copy.sub} back={() => router.replace(routeForRole(account.role) as never)} /><Card style={styles.account}><View style={styles.avatar}><MaterialIcons name="person" size={28} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.name}>{account.fullName}</Text><Text style={styles.role}>{role}</Text><Text style={styles.email}>{account.email}</Text></View></Card><Text style={styles.section}>{copy.account}</Text><SettingRow icon="lock-outline" title={copy.password} detail={copy.passwordDetail} open={copy.open} onPress={() => router.push("/change-password" as never)} /><SettingRow icon="person-outline" title={copy.profile} detail={copy.profileDetail} open={copy.open} onPress={() => router.push("/account-profile" as never)} /><Text style={styles.section}>{copy.language}</Text><Card style={styles.language}><Text style={styles.languageText}>{copy.choose}</Text><View style={styles.languageButtons}><LanguageButton label="Af-Soomaali" active={language === "so"} onPress={() => setLanguage("so")} /><LanguageButton label="English" active={language === "en"} onPress={() => setLanguage("en")} /></View></Card><Text style={styles.section}>{copy.appearance}</Text><Card style={styles.theme}><View style={styles.themeMarks}><View style={[styles.dot, { backgroundColor: "#FFFFFF" }]} /><View style={[styles.dot, { backgroundColor: "#111111" }]} /></View><View style={{ flex: 1 }}><Text style={styles.themeTitle}>{copy.mono}</Text><Text style={styles.themeText}>{copy.monoDetail}</Text></View></Card><Text style={styles.section}>{copy.session}</Text><SecondaryButton label={copy.logout} icon="logout" onPress={signOut} /></ScrollView></Page>;
}

function LanguageButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.languageButton, active && styles.languageButtonOn, pressed && styles.pressed]}><MaterialIcons name={active ? "radio-button-checked" : "radio-button-unchecked"} size={19} color={active ? "#FFFFFF" : palette.ink} /><Text style={[styles.languageButtonText, active && styles.languageButtonTextOn]}>{label}</Text></Pressable>; }
function SettingRow({ icon, title, detail, open, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; open: string; onPress: () => void }) { return <Card style={styles.setting}><View style={styles.settingIcon}><MaterialIcons name={icon} size={21} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingDetail}>{detail}</Text></View><SecondaryButton label={open} icon="chevron-right" onPress={onPress} /></Card>; }

const styles = StyleSheet.create({
  scroll: { gap: 13, paddingBottom: 30 }, account: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: palette.lavender }, avatar: { height: 55, width: 55, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line }, name: { color: palette.ink, fontSize: 17, fontWeight: "900" }, role: { color: palette.purple, fontSize: 11, fontWeight: "900", marginTop: 2 }, email: { color: palette.muted, fontSize: 11, marginTop: 4 }, section: { color: palette.ink, fontWeight: "900", letterSpacing: 1.1, fontSize: 10, marginTop: 7 }, setting: { flexDirection: "row", alignItems: "center", gap: 10, padding: 13 }, settingIcon: { height: 41, width: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: palette.blue }, settingTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, settingDetail: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, language: { gap: 12, backgroundColor: palette.paper }, languageText: { color: palette.muted, fontSize: 12, lineHeight: 18 }, languageButtons: { flexDirection: "row", gap: 8 }, languageButton: { flex: 1, minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: palette.line, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center", backgroundColor: palette.lavender }, languageButtonOn: { backgroundColor: palette.purple, borderColor: palette.purple }, languageButtonText: { color: palette.ink, fontSize: 12, fontWeight: "900" }, languageButtonTextOn: { color: "#FFFFFF" }, theme: { flexDirection: "row", gap: 12, alignItems: "center", backgroundColor: palette.blue }, themeMarks: { flexDirection: "row", height: 42, width: 58, borderRadius: 15, padding: 7, alignItems: "center", justifyContent: "space-between", backgroundColor: palette.purple }, dot: { height: 12, width: 12, borderRadius: 6 }, themeTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, themeText: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
