import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as ImageManipulator from "expo-image-manipulator";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, ProgressLine, SecondaryButton } from "@/components/iftiin-ui";
import { QUESTIONNAIRE, type ChoiceAnswer, type VisualObservation } from "@/lib/skin-care";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { useCart } from "@/lib/cart-context";
import { trpc } from "@/lib/trpc";
import { getApiBaseUrl } from "@/constants/oauth";

type Stage = "start" | "review" | "observation" | "questions" | "creating" | "preview";

export default function SkinJourneyScreen() { return <RequireRole role="customer"><SkinJourneyContent /></RequireRole>; }
function SkinJourneyContent() {
  const { session } = usePhaseSession();
  const [stage, setStage] = useState<Stage>("start"); const [photoUri, setPhotoUri] = useState(""); const [answers, setAnswers] = useState<Record<string, ChoiceAnswer>>({}); const [questionIndex, setQuestionIndex] = useState(0); const [visual, setVisual] = useState<VisualObservation>(); const [journey, setJourney] = useState<{ id: number; concerns: string[]; recommendedProduct: { id: number; name: string; brand: string; imageUrl: string | null; description: string | null; finalPrice: number } }>(); const [error, setError] = useState("");
  const analysis = trpc.skinAnalysis.analyzeFace.useMutation(); const createJourney = trpc.phase1.createSkinJourney.useMutation(); const question = QUESTIONNAIRE[questionIndex];
  async function choosePhoto(camera: boolean) { if (camera) { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (permission.status !== "granted") { Alert.alert("Oggolaansho loo baahan yahay", "Kamaraddu waxay u baahan tahay oggolaanshahaaga si sawir wejiga loo qaado."); return; } } const picked = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [3, 4], quality: 0.8, cameraType: ImagePicker.CameraType.front }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [3, 4], quality: 0.8 }); if (!picked.canceled) { setPhotoUri(picked.assets[0].uri); setAnswers({}); setVisual(undefined); setQuestionIndex(0); setError(""); setStage("review"); } }
  async function compact(uri: string) { const output = await ImageManipulator.manipulateAsync(uri, [{ resize: { width: 512 } }], { compress: 0.45, format: ImageManipulator.SaveFormat.JPEG, base64: true }); if (!output.base64 || output.base64.length > 340000) throw new Error("Sawirku aad ayuu u weyn yahay. Fadlan sawir kale qaad."); return `data:image/jpeg;base64,${output.base64}`; }
  async function beginQuestions() { try { const observed = await analysis.mutateAsync({ sessionToken: session!.token, faceImage: await compact(photoUri) }) as VisualObservation; setVisual(observed); setAnswers({ visibleConcerns: observed.calaamado }); setStage("observation"); } catch (issue) { setError(issue instanceof Error ? issue.message : "Sawirka lama qiimeyn karo hadda."); } }
  function next() { if (!answers[question.id]) return; if (questionIndex < QUESTIONNAIRE.length - 1) { setQuestionIndex((value) => value + 1); return; } setStage("creating"); createJourney.mutate({ sessionToken: session!.token, answers, visual }, { onSuccess: (result) => { setJourney(result); setStage("preview"); }, onError: (issue) => { setError(issue.message); setStage("questions"); } }); }
  if (stage === "start") return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Skin Journey" subtitle="Sawir, su’aalo, iyo talo hordhac ah" back={() => router.back()} /><View style={styles.hero}><MaterialIcons name="face-3" size={88} color={palette.purple} /><Text style={styles.heroTitle}>Aan eegno maqaarkaaga</Text><Text style={styles.heroCopy}>Waxaan sameynaa qiimeyn muuqaal iyo jawaabo ku salaysan oo hordhac ah. Tani ma aha diagnosis caafimaad.</Text></View><Card style={styles.card}><Text style={styles.cardTitle}>Si sawirku u caddaado</Text><Text style={styles.copy}>Isticmaal iftiin wanaagsan, filter ha isticmaalin, wajigaaga si toos ah u jeedi.</Text></Card><PrimaryButton label="Qaado sawirka wejiga" icon="photo-camera" onPress={() => choosePhoto(true)} /><SecondaryButton label="Ka dooro gallery" icon="photo-library" onPress={() => choosePhoto(false)} /></ScrollView></Page>;
  if (stage === "review") return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Hubi sawirka" back={() => setStage("start")} /><Image source={{ uri: photoUri }} style={styles.photo} /><Card style={styles.card}><Text style={styles.cardTitle}>Oggolaansho</Text><Text style={styles.copy}>Markaad sii waddo, sawirka waxaa loo diraa adeeg qiimeyn kara calaamado muuqaal ahaan cad oo daryeel maqaarka ah. Ma oga cudur, xasaasiyad, ama daaweyn.</Text></Card>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={analysis.isPending ? "Sawirka ayaa la eegayaa..." : "Oggolow oo sii wad"} onPress={beginQuestions} disabled={analysis.isPending} /><SecondaryButton label="Sawir kale qaado" icon="refresh" onPress={() => setStage("start")} /></ScrollView></Page>;
  if (stage === "observation" && visual) return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Waxa sawirka ka muuqda" subtitle="Qiimeyn muuqaal oo hordhac ah" back={() => setStage("review")} /><Image source={{ uri: photoUri }} style={styles.photo} /><Card style={styles.observation}><MaterialIcons name="visibility" size={27} color={palette.purple} /><Text style={styles.cardTitle}>{visual.sooKoobid}</Text><Text style={styles.copy}>Kuwaani waa calaamado muuqaal ahaan la arkay, mana aha diagnosis caafimaad. Su’aalaha xiga ayaa naga caawinaya inaan fahanno daryeelka ku habboon.</Text><View style={styles.tags}>{visual.calaamado.length ? visual.calaamado.map((item) => <View key={item} style={styles.tag}><Text style={styles.tagText}>{item}</Text></View>) : <View style={styles.tag}><Text style={styles.tagText}>Calaamad cad lama arkin</Text></View>}</View></Card><PrimaryButton label="Bilow su’aalaha" icon="arrow-forward" onPress={() => setStage("questions")} /></ScrollView></Page>;
  if (stage === "questions") return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Su’aalaha maqaarka" subtitle={`${questionIndex + 1} / ${QUESTIONNAIRE.length}`} back={() => questionIndex ? setQuestionIndex((value) => value - 1) : setStage("observation")} /><ProgressLine value={((questionIndex + 1) / QUESTIONNAIRE.length) * 100} /><View style={styles.context}><Image source={{ uri: photoUri }} style={styles.thumb} /><View><Text style={styles.contextLabel}>SAWIRKA WEJIGA</Text><Text style={styles.contextText}>Sawirkaagii wali wuu muuqdaa inta su’aaluhu socdaan.</Text></View></View><Text style={styles.question}>{question.title}</Text>{question.hint ? <Text style={styles.copy}>{question.hint}</Text> : null}<View style={styles.options}>{question.options.map((option) => { const selected = answers[question.id] === option; return <Pressable key={option} onPress={() => setAnswers((current) => ({ ...current, [question.id]: option }))} style={[styles.option, selected && styles.optionOn]}><MaterialIcons name={selected ? "radio-button-checked" : "radio-button-unchecked"} size={20} color={palette.purple} /><Text style={[styles.optionText, selected && styles.optionTextOn]}>{option}</Text></Pressable>; })}</View>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={questionIndex === QUESTIONNAIRE.length - 1 ? "Eeg natiijada hordhaca ah" : "Sii wad"} onPress={next} disabled={!answers[question.id]} /></ScrollView></Page>;
  if (stage === "creating") return <LoadingCare />;
  if (stage === "preview" && journey) return <Preview journey={journey} sessionToken={session!.token} />;
  return null;
}

function Preview({ journey, sessionToken }: { journey: { id: number; concerns: string[]; recommendedProduct: { id: number; name: string; brand: string; imageUrl: string | null; description: string | null; finalPrice: number } }; sessionToken: string }) { const product = trpc.phase1.customerProductDetail.useQuery({ sessionToken, productId: journey.recommendedProduct.id }); const cart = useCart(); const detail = product.data; function buyNow() { if (!detail) return; cart.clear(); const accepted = cart.add({ productId: detail.id, storeAdminId: detail.storeAdminId, storeName: detail.storeName, name: detail.name, brand: detail.brand, imageUrl: detail.imageUrl, originalPrice: detail.originalPrice, finalPrice: detail.finalPrice, stock: detail.stock, deliveryEnabled: detail.deliveryEnabled, deliveryFee: detail.deliveryFee, deliveryAreas: detail.deliveryAreas }); if (!accepted.accepted) { Alert.alert("Cart", accepted.reason ?? "Product-kan lama gelin karo."); return; } router.push({ pathname: "/cart" as never, params: { skinJourneyId: String(journey.id) } }); }
  return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Natiijo hordhac ah" subtitle="Natiijada buuxda waxay furmaysaa marka payment la xaqiijiyo" /><Card style={styles.preview}><MaterialIcons name="lock-outline" size={30} color={palette.purple} /><Text style={styles.previewTitle}>Waxaan helnay dhowr arrimood oo u baahan daryeel</Text><Text style={styles.copy}>Kani waa preview muuqaal iyo jawaabo ku salaysan; ma aha diagnosis caafimaad.</Text><View style={styles.tags}>{journey.concerns.length ? journey.concerns.map((item) => <View key={item} style={styles.tag}><Text style={styles.tagText}>{item}</Text></View>) : <View style={styles.tag}><Text style={styles.tagText}>Daryeel joogto ah</Text></View>}</View></Card><Text style={styles.unlockCopy}>Si aad u hesho natiijadaada oo dhamaystiran, talooyinka, routine-ka iyo Daily Skin Scan, iibi product-ka laguu doortay, kadib sug Store Admin inuu xaqiijiyo lacagta.</Text>{product.isLoading ? <LoadingCare /> : detail ? <Card style={styles.product}>{detail.imageUrl ? <Image source={{ uri: `${getApiBaseUrl()}${detail.imageUrl}` }} style={styles.productImage} /> : <View style={styles.productImage}><MaterialIcons name="inventory-2" size={34} color={palette.purple} /></View>}<View style={styles.productCopy}><Text style={styles.productName}>{detail.name}</Text><Text style={styles.brand}>{detail.brand}</Text><Text style={styles.price}>{detail.finalPrice}</Text><Text style={styles.description}>{detail.description || "Product-kan waxaa loo doortay inuu taageero daryeelka maqaarkaaga ee hordhaca ah."}</Text><Text style={styles.why}>Sababta loo doortay: wuxuu la jaanqaadaa calaamadaha hordhaca ah iyo baahida aad sheegtay.</Text></View></Card> : <EmptyState icon="inventory-2" title="Product-ka lama heli karo" detail="Fadlan dib u bilow scan-ka ama dooro product kale oo dukaanka ah." />}{detail ? <PrimaryButton label="Iibso hadda" icon="shopping-cart" onPress={buyNow} /> : null}<SecondaryButton label="Ku noqo hoyga" icon="home" onPress={() => router.replace("/customer-home" as never)} /></ScrollView></Page>; }
const styles = StyleSheet.create({ page: { gap: 14, paddingBottom: 30 }, hero: { alignItems: "center", padding: 26, gap: 9, borderRadius: 26, backgroundColor: palette.lavender }, heroTitle: { color: palette.ink, fontSize: 23, fontWeight: "900" }, heroCopy: { color: palette.muted, lineHeight: 19, fontSize: 12, textAlign: "center" }, card: { gap: 8 }, cardTitle: { color: palette.ink, fontSize: 15, fontWeight: "900" }, copy: { color: palette.muted, fontSize: 12, lineHeight: 18 }, photo: { width: "100%", height: 340, borderRadius: 24, backgroundColor: palette.lavender }, error: { color: "#A5264B", fontSize: 12, lineHeight: 17 }, observation: { gap: 10, backgroundColor: palette.blue }, context: { flexDirection: "row", gap: 10, alignItems: "center", padding: 10, borderRadius: 15, backgroundColor: palette.blue }, thumb: { height: 52, width: 45, borderRadius: 10 }, contextLabel: { color: palette.purple, fontSize: 10, fontWeight: "900" }, contextText: { color: palette.ink, fontSize: 11, lineHeight: 15, marginTop: 3, maxWidth: 230 }, question: { color: palette.ink, fontSize: 23, lineHeight: 30, fontWeight: "900", marginTop: 5 }, options: { gap: 8 }, option: { flexDirection: "row", gap: 10, alignItems: "center", padding: 14, borderColor: palette.line, borderWidth: 1, borderRadius: 15, backgroundColor: "#FFF" }, optionOn: { borderColor: palette.purple, backgroundColor: palette.lavender }, optionText: { color: palette.ink, flex: 1, fontSize: 13, fontWeight: "700" }, optionTextOn: { color: palette.purple }, preview: { alignItems: "center", gap: 9, backgroundColor: palette.blue }, previewTitle: { color: palette.ink, fontWeight: "900", fontSize: 18, textAlign: "center" }, tags: { flexDirection: "row", flexWrap: "wrap", gap: 7, justifyContent: "center" }, tag: { backgroundColor: "#FFF", paddingVertical: 7, paddingHorizontal: 9, borderRadius: 11 }, tagText: { color: palette.purple, fontWeight: "800", fontSize: 11 }, unlockCopy: { color: palette.ink, fontSize: 13, lineHeight: 20, fontWeight: "700" }, product: { flexDirection: "row", gap: 11, alignItems: "flex-start" }, productImage: { height: 86, width: 76, borderRadius: 14, backgroundColor: palette.lavender }, productCopy: { flex: 1, gap: 3 }, productName: { color: palette.ink, fontSize: 14, fontWeight: "900" }, brand: { color: palette.muted, fontSize: 11 }, price: { color: palette.purple, fontSize: 17, fontWeight: "900" }, description: { color: palette.muted, fontSize: 11, lineHeight: 16 }, why: { color: palette.ink, fontSize: 11, lineHeight: 16, fontWeight: "700", marginTop: 3 } });
