import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function SkinRoutineScreen() { return <RequireRole role="customer"><RoutineContent /></RequireRole>; }
function RoutineContent() { const { session } = usePhaseSession(); const { journeyId: raw } = useLocalSearchParams<{ journeyId: string }>(); const journeyId = Number(raw); const result = trpc.phase1.fullSkinJourney.useQuery({ sessionToken: session!.token, journeyId: Number.isInteger(journeyId) && journeyId > 0 ? journeyId : 1 }, { enabled: Number.isInteger(journeyId) && journeyId > 0 }); if (result.isLoading) return <LoadingCare />; if (result.error || !result.data) return <Page><Header title="Routine-kaaga" back={() => router.back()} /><EmptyState icon="lock-outline" title="Routine-ku wali ma furna" detail="Routine-ku wuxuu furmaa oo keliya payment la xaqiijiyey kadib." /></Page>; const product = result.data.recommendedProduct;
  const usageLine = product.usageInstructions ? `${product.name}: ${product.usageInstructions}` : `${product.name}: ku mari sida ku qoran baakadka.`;
  return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Routine-kaaga" subtitle="Subax, fiid, iyo qorshe bille ah" back={() => router.back()} /><Card style={styles.intro}><MaterialIcons name="spa" size={29} color={palette.purple} /><Text style={styles.introTitle}>Ku soco si tartiib ah</Text><Text style={styles.copy}>Raac tilmaamaha baakadka product-ka. Haddii aad dareento gubasho, barar ama falcelin xoog leh, jooji isticmaalka oo la xiriir xirfadle caafimaad.</Text></Card><RoutineBlock icon="wb-sunny" title="Subax" steps={["Nadiifi wejiga si khafiif ah.", usageLine, "Haddii product-kaagu leeyahay ilaalin qorrax, mari kahor bannaanka."]} /><RoutineBlock icon="nightlight-round" title="Fiid" steps={["Nadiifi wejiga si khafiif ah.", usageLine, "Ha isku darin alaabo badan hal mar."]} /><Card style={styles.month}><Text style={styles.monthTitle}>Qorshaha 28-ka maalmood</Text><Text style={styles.copy}>Maalin kasta ku calaamadee routine-kaaga, qaado Daily Scan marka aad rabto inaad barbar dhigto sawirrada, kuna joog hal nidaam oo deggan.</Text></Card><PrimaryButton label="Daily Skin Scan" icon="add-a-photo" onPress={() => router.push({ pathname: "/daily-skin-scan" as never, params: { journeyId: String(journeyId) } })} /><SecondaryButton label="Horumarkayga" icon="insights" onPress={() => router.push({ pathname: "/skin-progress" as never, params: { journeyId: String(journeyId) } })} /></ScrollView></Page>; }
function RoutineBlock({ icon, title, steps }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; steps: string[] }) { return <Card style={styles.block}><View style={styles.blockHead}><MaterialIcons name={icon} size={21} color={palette.purple} /><Text style={styles.blockTitle}>{title}</Text></View>{steps.map((step, index) => <View key={step} style={styles.step}><Text style={styles.number}>{index + 1}</Text><Text style={styles.stepText}>{step}</Text></View>)}</Card>; }
const styles = StyleSheet.create({ page: { gap: 13, paddingBottom: 30 }, intro: { gap: 7, backgroundColor: palette.blue }, introTitle: { color: palette.ink, fontSize: 18, fontWeight: "900" }, copy: { color: palette.muted, fontSize: 12, lineHeight: 18 }, block: { gap: 11 }, blockHead: { flexDirection: "row", gap: 8, alignItems: "center" }, blockTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" }, step: { flexDirection: "row", gap: 9, alignItems: "flex-start" }, number: { color: palette.purple, fontWeight: "900", fontSize: 12, backgroundColor: palette.lavender, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10 }, stepText: { color: palette.ink, fontSize: 12, lineHeight: 18, flex: 1 }, month: { gap: 7, backgroundColor: palette.lavender }, monthTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" } });