import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton } from "@/components/iftiin-ui";
import { useCare } from "@/lib/skin-care-context";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function SkinProgressScreen() { return <RequireRole role="customer"><ProgressContent /></RequireRole>; }
function ProgressContent() { const { session } = usePhaseSession(); const { journeyId: raw } = useLocalSearchParams<{ journeyId: string }>(); const journeyId = Number(raw); const unlock = trpc.phase1.fullSkinJourney.useQuery({ sessionToken: session!.token, journeyId: Number.isInteger(journeyId) && journeyId > 0 ? journeyId : 1 }, { enabled: Number.isInteger(journeyId) && journeyId > 0 }); const { history, progress, toggleDailyItem, completeToday } = useCare(); if (unlock.isLoading) return <LoadingCare />; if (unlock.error || !unlock.data) return <Page><Header title="Horumarka maqaarka" back={() => router.back()} /><EmptyState icon="lock-outline" title="Horumarku wali ma furna" detail="Waxay furmaysaa oo keliya payment la xaqiijiyey kadib." /></Page>; const milestones = [1, 7, 14, 21, 28]; return <Page><ScrollView contentContainerStyle={styles.page}><Header title="Horumarka maqaarka" subtitle="Routine iyo sawirro la barbar dhigo" back={() => router.back()} /><Card style={styles.summary}><Text style={styles.summaryValue}>{progress.completedDays.length}/28</Text><Text style={styles.copy}>Maalmo routine la dhammaystiray. Ha filan natiijo caafimaad oo sawir keliya ku salaysan.</Text></Card><Card style={styles.checklist}><Text style={styles.title}>Checklist-ka maanta</Text>{["Nadiifi wejiga", "Isticmaal product-kaaga sida baakadka", "Ku qor isbeddel aad dareentay"].map((item, index) => <View key={item} style={styles.check}><MaterialIcons name={progress.dailyItems[`today-${index}`] ? "check-box" : "check-box-outline-blank"} size={21} color={palette.purple} onPress={() => toggleDailyItem(`today-${index}`)} /><Text style={styles.checkText}>{item}</Text></View>)}<PrimaryButton label="Dhammaystir maanta" icon="check-circle" onPress={completeToday} /></Card><Text style={styles.title}>Milestones</Text><View style={styles.milestones}>{milestones.map((day) => <View key={day} style={[styles.milestone, progress.completedDays.includes(day) && styles.milestoneOn]}><Text style={styles.milestoneText}>Day {day}</Text></View>)}</View><Text style={styles.title}>Sawirrada</Text>{history.length ? history.map((item) => <Card key={item.id} style={styles.scan}><Image source={{ uri: item.photoUri }} style={styles.scanPhoto} /><View style={{ flex: 1 }}><Text style={styles.scanTitle}>{item.daySlot}</Text><Text style={styles.copy}>{new Date(item.createdAt).toLocaleDateString()}</Text><Text style={styles.copy}>{item.visual?.sooKoobid || "Sawirkan waxaa loo kaydiyey isbarbardhig muuqaal."}</Text></View></Card>) : <EmptyState icon="photo-library" title="Sawirro lama hayo" detail="Qaado Daily Skin Scan si aad horumarkaaga u aragto." />}<PrimaryButton label="Qaado Daily Scan" icon="add-a-photo" onPress={() => router.push({ pathname: "/daily-skin-scan" as never, params: { journeyId: String(journeyId) } })} /></ScrollView></Page>; }
const styles = StyleSheet.create({ page: { gap: 13, paddingBottom: 30 }, summary: { backgroundColor: palette.blue, gap: 5 }, summaryValue: { color: palette.purple, fontSize: 30, fontWeight: "900" }, copy: { color: palette.muted, fontSize: 11, lineHeight: 17 }, checklist: { gap: 10 }, title: { color: palette.ink, fontSize: 16, fontWeight: "900" }, check: { flexDirection: "row", gap: 9, alignItems: "center" }, checkText: { color: palette.ink, flex: 1, fontSize: 12 }, milestones: { flexDirection: "row", justifyContent: "space-between", gap: 5 }, milestone: { flex: 1, alignItems: "center", paddingVertical: 10, backgroundColor: palette.lavender, borderRadius: 10 }, milestoneOn: { backgroundColor: palette.purple }, milestoneText: { color: palette.ink, fontSize: 10, fontWeight: "900" }, scan: { flexDirection: "row", gap: 10, alignItems: "center" }, scanPhoto: { width: 68, height: 82, borderRadius: 12, backgroundColor: palette.lavender }, scanTitle: { color: palette.ink, fontSize: 13, fontWeight: "900", marginBottom: 3 } });
