import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function StoreAdminDashboard() { return <RequireRole role="store_admin"><StoreDashboard /></RequireRole>; }
function StoreDashboard() { const { session } = usePhaseSession(); const dashboard = trpc.phase1.storeDashboard.useQuery({ sessionToken: session!.token }); const notificationSummary = trpc.phase1.notificationSummary.useQuery({ sessionToken: session!.token }); if (dashboard.isLoading) return <LoadingCare />; const account = dashboard.data?.account; const restricted = account?.status === "restricted"; return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title="Dashboard-ka dukaanka" subtitle="Awooddaadu waxay ku kooban tahay dukaankaaga" /><View style={styles.hero}><View style={styles.icon}><MaterialIcons name="storefront" size={28} color={palette.purple} /></View><Text style={styles.title}>{account?.storeName}</Text><Text style={styles.copy}>Maamul product-yada, stock-ga, qiimaha, delivery-ga, iyo dalabyada dukaankaaga oo keliya.</Text></View>{restricted ? <Card style={styles.restricted}><MaterialIcons name="warning-amber" size={22} color={palette.warning} /><Text style={styles.restrictedText}>Commission payment is required. Your store cannot receive new orders until Super Admin verifies the commission.</Text></Card> : null}<Card><Text style={styles.label}>MILKIILAHA</Text><Text style={styles.value}>{account?.fullName}</Text><Text style={styles.label}>GOOBTA</Text><Text style={styles.value}>{account?.location}</Text><Text style={styles.label}>XAAWALADDA</Text><Text style={restricted ? styles.restrictedStatus : styles.active}>{restricted ? "RESTRICTED" : "Firfircoon"}</Text></Card><SecondaryButton label="Maaree alaabta" icon="inventory-2" onPress={() => router.push("/store-products" as never)} /><SecondaryButton label="Dalabyada dukaanka" icon="receipt-long" onPress={() => router.push("/store-orders" as never)} /><SecondaryButton label="5% Commission" icon="account-balance-wallet" onPress={() => router.push("/store-commissions" as never)} /><SecondaryButton label="Dejinta lacagaha" icon="account-balance-wallet" onPress={() => router.push("/store-payment-settings" as never)} /><SecondaryButton label="Ogeysiisyada" icon="notifications" badge={notificationSummary.data?.unreadCount} onPress={() => router.push("/notifications" as never)} /><SecondaryButton label="Delivery settings" icon="local-shipping" onPress={() => router.push("/delivery-settings" as never)} /><SecondaryButton label="Qoraalkayga" icon="person" onPress={() => router.push("/account-profile" as never)} /></ScrollView></Page>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, hero: { backgroundColor: palette.lavender, borderRadius: 25, padding: 22, gap: 7 }, icon: { width: 52, height: 52, borderRadius: 18, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, title: { color: palette.ink, fontSize: 23, fontWeight: "900" }, copy: { color: palette.muted, fontSize: 13, lineHeight: 20 }, restricted: { flexDirection: "row", gap: 9, alignItems: "center", backgroundColor: "#FFF5DE", borderColor: "#F2D38A", borderWidth: 1 }, restrictedText: { flex: 1, color: palette.warning, fontSize: 11, lineHeight: 16, fontWeight: "800" }, label: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 10 }, value: { color: palette.ink, fontSize: 15, fontWeight: "800", marginTop: 3 }, active: { color: palette.success, fontSize: 14, fontWeight: "900", marginTop: 3 }, restrictedStatus: { color: palette.warning, fontSize: 14, fontWeight: "900", marginTop: 3 } });
