import { router } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useMemo, useState } from "react";

import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { pending: "Sugaya lacag-bixin", payment_confirmed: "Payment Confirmed", processing: "Processing", ready: "Ready", out_for_delivery: "Out for Delivery", delivered: "Delivered", completed: "Completed", cancelled: "Cancelled", confirmed: "La xaqiijiyey (hore)", preparing: "Diyaar garow (hore)" };
const paymentLabels: Record<string, string> = { pending_payment: "Pending Payment", sent_awaiting_confirmation: "Payment Sent / Awaiting Confirmation", confirmed: "Paid", rejected: "Payment Rejected", failed: "Payment Failed" };
const methodLabels: Record<string, string> = { evc_plus: "EVC Plus", edahab: "eDahab", premier_wallet: "Premier Wallet", merchant: "Merchant" };
type UpdateStatus = "processing" | "ready" | "out_for_delivery" | "delivered" | "completed" | "cancelled";
const nextStatus: Record<string, { key: UpdateStatus; label: string }[]> = { pending: [{ key: "cancelled", label: "Cancel Order" }], payment_confirmed: [{ key: "processing", label: "Start Processing" }, { key: "cancelled", label: "Cancel Order" }], processing: [{ key: "ready", label: "Mark Ready" }, { key: "cancelled", label: "Cancel Order" }], ready: [{ key: "out_for_delivery", label: "Out for Delivery" }, { key: "cancelled", label: "Cancel Order" }], out_for_delivery: [{ key: "delivered", label: "Mark Delivered" }, { key: "cancelled", label: "Cancel Order" }], delivered: [{ key: "completed", label: "Complete Order" }], completed: [], cancelled: [], confirmed: [{ key: "processing", label: "Start Processing" }, { key: "cancelled", label: "Cancel Order" }], preparing: [{ key: "ready", label: "Mark Ready" }, { key: "cancelled", label: "Cancel Order" }] };

export default function StoreOrders() { return <RequireRole role="store_admin"><OrdersContent /></RequireRole>; }

function OrdersContent() {
  const { session } = usePhaseSession();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("dhammaan");
  const orders = trpc.phase1.storeOrders.useQuery({ sessionToken: session!.token });
  const update = trpc.phase1.updateOrderStatus.useMutation({ onSuccess: () => orders.refetch() });
  const reviewPayment = trpc.phase1.reviewPayment.useMutation({ onSuccess: () => orders.refetch() });
  const visible = useMemo(() => (orders.data ?? []).filter((item) => { const text = `${item.id} ${item.customerName} ${item.items.map((line) => line.productName).join(" ")}`.toLowerCase(); return (filter === "dhammaan" || item.status === filter) && (!search.trim() || text.includes(search.trim().toLowerCase())); }), [orders.data, search, filter]);
  if (orders.isLoading) return <LoadingCare />;
  const change = (orderId: number, status: UpdateStatus, label: string) => Alert.alert("Beddel xaaladda", `Ma u beddeshaa ${label}? Customer-ka wuxuu heli doonaa ogeysiin.`, [{ text: "Jooji", style: "cancel" }, { text: "Haa", style: status === "cancelled" ? "destructive" : "default", onPress: () => update.mutate({ sessionToken: session!.token, orderId, status }) }]);
  const review = (orderId: number, status: "confirmed" | "rejected") => { const confirm = status === "confirmed"; Alert.alert(confirm ? "Xaqiiji lacagta" : "Diid lacagta", confirm ? "Hubi akoonkaaga dhabta ah. Marka lacagta la helo, dalabku wuxuu geli doonaa Payment Confirmed." : "Ma hubisay in lacagtu aanay soo gelin? Dalabku wuxuu ahaanayaa unpaid.", [{ text: "Jooji", style: "cancel" }, { text: confirm ? "Haa, waan helay" : "Haa, diid", style: confirm ? "default" : "destructive", onPress: () => reviewPayment.mutate({ sessionToken: session!.token, orderId, status }) }]); };
  const detail = (orderId: number) => router.push({ pathname: "/order-detail" as never, params: { orderId: String(orderId) } });
  const filters = ["dhammaan", "pending", "payment_confirmed", "processing", "ready", "out_for_delivery", "delivered", "completed", "cancelled"];
  return <Page noPadding><FlatList data={visible} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Dalabyada dukaanka" subtitle="Lacagta xaqiiji, kadibna maamul socodka dalabka" back={() => router.back()} /><View style={styles.search}><TextInput value={search} onChangeText={setSearch} placeholder="Raadi dalab, customer ama product" placeholderTextColor="#7B9AAF" style={styles.input} /></View><View style={styles.filters}>{filters.map((value) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterOn]}><Text style={[styles.filterText, filter === value && styles.filterTextOn]}>{value === "dhammaan" ? "Dhammaan" : labels[value]}</Text></Pressable>)}</View></View>} ListEmptyComponent={<EmptyState icon="receipt-long" title="Dalab lama helin" detail="Beddel search-ka ama filter-ka si aad u aragto dalabyada dukaankaaga." />} renderItem={({ item }) => {
    const payment = item.payment;
    const paid = !payment || payment.status === "confirmed";
    return <Card style={styles.order}><View style={styles.top}><View><Text style={styles.orderId}>Dalab #{item.id}</Text><Text style={styles.customer}>Customer: {item.customerName}</Text></View><View style={styles.badge}><Text style={styles.badgeText}>{labels[item.status]}</Text></View></View><View style={styles.lines}>{item.items.map((line) => <View key={line.id} style={styles.productRow}><Text style={styles.productName}>{line.productName} × {line.quantity}</Text><Text style={styles.productPrice}>{line.finalPrice} · {line.lineTotal}</Text></View>)}</View><View style={styles.costs}><Cost label="Subtotal" value={item.subtotal} /><Cost label="Discount" value={`-${item.discount}`} /><Cost label="Delivery fee" value={item.deliveryFee} /><Cost label="Total" value={item.total} strong /></View>{item.deliveryArea ? <Text style={styles.delivery}>Delivery: {item.deliveryArea}</Text> : <Text style={styles.delivery}>Dukaanka ayaa laga qaadanayaa</Text>}{payment ? <View style={[styles.paymentRow, payment.status === "confirmed" && styles.paymentPaid]}><Text style={styles.paymentLabel}>{paymentLabels[payment.status]}</Text><Text style={styles.paymentAccount}>{methodLabels[payment.method] ?? payment.method} · {payment.amount}</Text></View> : null}<View style={styles.bottom}><Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString()}</Text><Pressable onPress={() => detail(item.id)} style={styles.detail}><Text style={styles.detailText}>Faahfaahin</Text></Pressable></View><View style={styles.actions}>{payment?.status === "sent_awaiting_confirmation" ? <><Pressable onPress={() => review(item.id, "confirmed")} style={styles.action}><Text style={styles.actionText}>{reviewPayment.isPending ? "Sug..." : "Confirm Payment"}</Text></Pressable><Pressable onPress={() => review(item.id, "rejected")} style={[styles.action, styles.cancel]}><Text style={[styles.actionText, styles.cancelText]}>Reject Payment</Text></Pressable></> : null}{(paid || item.status === "pending") ? (nextStatus[item.status] ?? []).map((action) => <Pressable key={action.key} onPress={() => change(item.id, action.key, action.label)} style={[styles.action, action.key === "cancelled" && styles.cancel]}><Text style={[styles.actionText, action.key === "cancelled" && styles.cancelText]}>{action.label}</Text></Pressable>) : null}</View>{payment && !paid && payment.status !== "sent_awaiting_confirmation" ? <Text style={styles.paymentHint}>Fulfilment lama bilaabi karo ilaa Payment Status uu noqdo Paid.</Text> : null}</Card>;
  }} /></Page>;
}

function Cost({ label, value, strong = false }: { label: string; value: string | number; strong?: boolean }) { return <View style={styles.costRow}><Text style={[styles.costLabel, strong && styles.costStrong]}>{label}</Text><Text style={[styles.costValue, strong && styles.costStrong]}>{value}</Text></View>; }

const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20, gap: 9 }, search: { height: 48, borderWidth: 1, borderColor: palette.line, borderRadius: 14, paddingHorizontal: 12 }, input: { color: palette.ink, flex: 1 }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, filter: { borderWidth: 1, borderColor: palette.line, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10 }, filterOn: { borderColor: palette.purple, backgroundColor: palette.lavender }, filterText: { color: palette.muted, fontSize: 10, fontWeight: "800" }, filterTextOn: { color: palette.purple }, order: { marginHorizontal: 20, gap: 8 }, top: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, orderId: { color: palette.ink, fontSize: 14, fontWeight: "900" }, customer: { color: palette.muted, fontSize: 11, marginTop: 3 }, badge: { backgroundColor: palette.lavender, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 5, maxWidth: 132 }, badgeText: { color: palette.purple, fontSize: 10, fontWeight: "900", textAlign: "right" }, lines: { gap: 5 }, productRow: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, productName: { color: palette.ink, fontSize: 11, fontWeight: "700", flex: 1 }, productPrice: { color: palette.muted, fontSize: 10 }, costs: { gap: 3, borderTopWidth: 1, borderTopColor: palette.line, paddingTop: 8 }, costRow: { flexDirection: "row", justifyContent: "space-between" }, costLabel: { color: palette.muted, fontSize: 10 }, costValue: { color: palette.ink, fontSize: 10, fontWeight: "800" }, costStrong: { color: palette.purple, fontSize: 12, fontWeight: "900" }, delivery: { color: palette.ink, fontSize: 11, fontWeight: "700" }, paymentRow: { padding: 9, backgroundColor: palette.lavender, borderRadius: 11, gap: 3 }, paymentPaid: { backgroundColor: palette.blue }, paymentLabel: { color: palette.ink, fontSize: 11, fontWeight: "900" }, paymentAccount: { color: palette.muted, fontSize: 10 }, bottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderTopColor: palette.line, borderTopWidth: 1, paddingTop: 9 }, date: { color: palette.muted, fontSize: 10 }, detail: { backgroundColor: palette.lavender, paddingVertical: 7, paddingHorizontal: 9, borderRadius: 9 }, detailText: { color: palette.purple, fontWeight: "900", fontSize: 10 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 3 }, action: { backgroundColor: palette.lavender, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 }, actionText: { color: palette.purple, fontWeight: "900", fontSize: 11 }, cancel: { backgroundColor: "#FDECEF" }, cancelText: { color: palette.danger }, paymentHint: { color: palette.warning, fontSize: 10, lineHeight: 15, fontWeight: "800" } });
