import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";
const labels: Record<string, string> = { pending: "Sugaya lacag-bixin", payment_confirmed: "Payment Confirmed", processing: "Processing", ready: "Ready", out_for_delivery: "Out for Delivery", delivered: "Delivered", completed: "Completed", cancelled: "Cancelled", confirmed: "La xaqiijiyey (hore)", preparing: "Diyaar garow (hore)" };
export default function SuperAdminOrders() { return <RequireRole role="super_admin"><AllOrders /></RequireRole>; }
function AllOrders() { const { session } = usePhaseSession(); const orders = trpc.phase1.allOrders.useQuery({ sessionToken: session!.token }); if (orders.isLoading) return <LoadingCare />; const detail = (orderId: number) => router.push({ pathname: "/order-detail" as never, params: { orderId: String(orderId) } }); return <Page noPadding><FlatList data={orders.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Dhammaan dalabyada" subtitle="Aragti Maamulaha Sare oo keliya" back={() => router.back()} /></View>} ListEmptyComponent={<EmptyState icon="receipt-long" title="Dalab ma jiro" detail="Dalabyada dukaamada ayaa halkan kasoo muuqan doona." />} renderItem={({ item }) => <Card style={styles.order}><View style={styles.top}><View><Text style={styles.orderId}>Dalab #{item.id}</Text><Text style={styles.names}>{item.customerName} → {item.storeName}</Text></View><View style={styles.badge}><Text style={styles.badgeText}>{labels[item.status]}</Text></View></View><Text style={styles.items}>{item.items.map((line) => `${line.productName} × ${line.quantity}`).join(" · ")}</Text><View style={styles.bottom}><Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString()}</Text><Text style={styles.total}>{item.total}</Text></View><Pressable onPress={() => detail(item.id)} style={styles.detail}><Text style={styles.detailText}>Eeg faahfaahinta</Text></Pressable></Card>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20 }, order: { marginHorizontal: 20, gap: 8 }, top: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, orderId: { color: palette.ink, fontSize: 14, fontWeight: "900" }, names: { color: palette.muted, fontSize: 11, marginTop: 3 }, badge: { backgroundColor: palette.lavender, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 5 }, badgeText: { color: palette.purple, fontSize: 10, fontWeight: "900" }, items: { color: palette.muted, fontSize: 11, lineHeight: 17 }, bottom: { flexDirection: "row", justifyContent: "space-between", borderTopColor: palette.line, borderTopWidth: 1, paddingTop: 9 }, date: { color: palette.muted, fontSize: 10 }, total: { color: palette.purple, fontWeight: "900", fontSize: 14 }, detail: { alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: palette.lavender }, detailText: { color: palette.purple, fontSize: 11, fontWeight: "900" } });
