import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { router } from "expo-router";
import { FlatList, Image, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { showAlert } from "@/lib/alert";

import { getApiBaseUrl } from "@/constants/oauth";
import { Card, EmptyState, Header, LoadingCare, Page, palette, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

const statusLabel: Record<string, string> = { required: "Commission required", commission_payment_sent: "Commission payment sent", paid: "Commission paid", rejected: "Commission rejected" };

export default function SuperAdminPayments() { return <RequireRole role="super_admin"><PaymentsDashboard /></RequireRole>; }

function PaymentsDashboard() {
  const { session } = usePhaseSession();
  const report = trpc.phase1.paymentDashboard.useQuery({ sessionToken: session!.token });
  const csv = trpc.phase1.commissionCsv.useQuery({ sessionToken: session!.token }, { enabled: false });
  const review = trpc.phase1.reviewCommissionPayment.useMutation({ onSuccess: () => report.refetch() });
  if (report.isLoading) return <LoadingCare />;
  if (report.error || !report.data) return <Page><Header title="Warbixinta commission-ka" back={() => router.back()} /><EmptyState icon="error-outline" title="Warbixinta lama heli karo" detail="Fadlan mar kale isku day." /></Page>;
  const data = report.data;
  const decide = (commissionId: number, status: "paid" | "rejected") => { const paid = status === "paid"; showAlert(paid ? "Xaqiiji commission-ka" : "Diid commission-ka", paid ? "Hubi akoonkaaga dhabta ah iyo receipt-ka haddii uu jiro. Marka la helo, dukaanka waa la furi karaa haddii uusan lahayn commission kale oo sugaysa." : "Ma hubisay in commission-kan aanu soo gelin? Dukaanka wuxuu ahaanayaa Restricted.", [{ text: "Jooji", style: "cancel" }, { text: paid ? "Haa, waan helay" : "Haa, diid", style: paid ? "default" : "destructive", onPress: () => review.mutate({ sessionToken: session!.token, commissionId, status }) }]); };
  const exportCsv = async () => { const result = await csv.refetch(); if (!result.data) { showAlert("CSV lama diyaarin karo", "Fadlan mar kale isku day."); return; } const { filename, csv: content } = result.data; try { if (Platform.OS === "web") { const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); return; } const uri = `${FileSystem.cacheDirectory}${filename}`; await FileSystem.writeAsStringAsync(uri, content, { encoding: FileSystem.EncodingType.UTF8 }); if (!(await Sharing.isAvailableAsync())) throw new Error("Qalabkan ma taageerayo share sheet."); await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Export commission history" }); } catch (issue) { showAlert("CSV lama dhoofin karo", issue instanceof Error ? issue.message : "Mar kale isku day."); } };
  return <Page noPadding><FlatList data={data.history} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Header title="Commission dashboard" subtitle="5% commission, xannibaadda dukaanka, iyo xaqiijinta" back={() => router.back()} /><SecondaryButton label={csv.isFetching ? "CSV waa la diyaarinayaa..." : "Export commission CSV"} icon="download" onPress={exportCsv} /><View style={styles.grid}><Stat icon="payments" label="Wadarta iibka" value={data.totalSales} tone={palette.blue} /><Stat icon="account-balance-wallet" label="5% commission" value={data.totalCommission} tone={palette.lavender} /><Stat icon="hourglass-top" label="Commission sugaysa" value={data.pendingCommissionCount} tone="#FFF2D8" /><Stat icon="verified" label="Commission Paid" value={data.paidCommissionCount} tone="#EAF8EF" /><Stat icon="storefront" label="Dakhli dukaamo" value={data.storeEarnings} tone="#F2F8FC" /></View><Text style={styles.historyTitle}>Store commission history</Text></View>} ListEmptyComponent={<EmptyState icon="account-balance-wallet" title="Commission ma jiro" detail="Marka Store Admin xaqiijiyo lacag-bixin customer, 5% commission-ka halkan ayuu kasoo muuqanayaa." />} renderItem={({ item }) => <Card style={styles.history}><View style={styles.historyTop}><View><Text style={styles.store}>{item.storeName}</Text><Text style={styles.order}>Dalab #{item.orderId} · {item.storeStatus === "restricted" ? "STORE RESTRICTED" : item.storeStatus}</Text></View><Text style={[styles.commission, item.status === "paid" && styles.paid]}>{item.commissionAmount}</Text></View><Text style={[styles.reminder, item.reminder.includes("dhacay") && styles.overdue]}>{item.reminder}{item.dueAt ? ` · Due: ${new Date(item.dueAt).toLocaleDateString()}` : ""}</Text><View style={styles.split}><Text style={styles.splitText}>Iib: {item.saleAmount}</Text><Text style={styles.splitText}>Dukaan: {item.storeEarnings}</Text><Text style={styles.splitText}>{statusLabel[item.status]}</Text></View>{item.receiptImageUrl ? <View style={styles.receipt}><Image source={{ uri: `${getApiBaseUrl()}${item.receiptImageUrl}` }} style={styles.receiptImage} /><Text style={styles.receiptText}>Receipt evidence (xaqiijin otomaatig ah ma aha)</Text></View> : null}{item.status === "commission_payment_sent" ? <View style={styles.actions}><Pressable onPress={() => decide(item.id, "paid")} style={styles.action}><Text style={styles.actionText}>{review.isPending ? "Sug..." : "Confirm commission"}</Text></Pressable><Pressable onPress={() => decide(item.id, "rejected")} style={[styles.action, styles.reject]}><Text style={[styles.actionText, styles.rejectText]}>Reject commission</Text></Pressable></View> : null}<Text style={styles.date}>{new Date(item.createdAt).toLocaleString()}</Text></Card>} /></Page>;
}

function Stat({ icon, label, value, tone }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; value: number; tone: string }) { return <Card style={[styles.stat, { backgroundColor: tone }]}><MaterialIcons name={icon} size={20} color={palette.purple} /><Text style={styles.value}>{value}</Text><Text style={styles.statLabel}>{label}</Text></Card>; }

const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, header: { paddingHorizontal: 20, gap: 12 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, stat: { width: "47%", gap: 3, padding: 13 }, value: { color: palette.ink, fontSize: 18, fontWeight: "900" }, statLabel: { color: palette.muted, fontSize: 10, fontWeight: "800" }, historyTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", marginTop: 5 }, history: { marginHorizontal: 20, gap: 8 }, historyTop: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, store: { color: palette.ink, fontSize: 13, fontWeight: "900" }, order: { color: palette.muted, fontSize: 10, marginTop: 3 }, commission: { color: palette.warning, fontSize: 16, fontWeight: "900" }, paid: { color: palette.success }, reminder: { color: palette.warning, fontSize: 10, lineHeight: 15, fontWeight: "800" }, overdue: { color: palette.danger }, split: { flexDirection: "row", gap: 11, flexWrap: "wrap" }, splitText: { color: palette.muted, fontSize: 10, fontWeight: "700" }, receipt: { flexDirection: "row", gap: 9, backgroundColor: palette.lavender, borderRadius: 12, padding: 8, alignItems: "center" }, receiptImage: { width: 54, height: 54, borderRadius: 8, backgroundColor: palette.paper }, receiptText: { flex: 1, color: palette.muted, fontSize: 10, lineHeight: 15 }, actions: { flexDirection: "row", gap: 8 }, action: { backgroundColor: palette.lavender, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 }, actionText: { color: palette.purple, fontSize: 10, fontWeight: "900" }, reject: { backgroundColor: "#FDECEF" }, rejectText: { color: palette.danger }, date: { color: palette.muted, borderTopColor: palette.line, borderTopWidth: 1, paddingTop: 8, fontSize: 10 } });
