import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { getApiBaseUrl } from "@/constants/oauth";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Image, StyleSheet, Text, TextInput, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function SuperAdminProductsScreen() { return <RequireRole role="super_admin"><AllProducts /></RequireRole>; }
function AllProducts() { const { session } = usePhaseSession(); const [search, setSearch] = useState(""); const products = trpc.phase1.allProducts.useQuery({ sessionToken: session!.token, search: search || undefined }); if (products.isLoading) return <LoadingCare />; return <Page noPadding><FlatList data={products.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.head}><Header title="Dhammaan alaabta" subtitle="Aragti Maamulaha Sare oo keliya" back={() => router.back()} /><View style={styles.search}><MaterialIcons name="search" size={20} color={palette.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Raadi product ama brand" style={styles.input} placeholderTextColor="#918FA0" /></View></View>} ListEmptyComponent={<EmptyState icon="inventory-2" title="Product ma jiro" detail="Dukaamada ayaa halkan ku soo dari doona product-yadooda." />} renderItem={({ item }) => <Card style={styles.product}><View style={styles.image}>{item.imageUrl ? <Image source={{ uri: `${getApiBaseUrl()}${item.imageUrl}` }} style={styles.imageFill} /> : <MaterialIcons name="inventory-2" size={23} color={palette.purple} />}</View><View style={{ flex: 1 }}><Text style={styles.store}>{item.storeName || "Dukaan"}</Text><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.brand} · {item.category}</Text><Text style={styles.detail}>${item.finalPrice} · {item.stock} xabo</Text></View></Card>} /></Page>; }
const styles = StyleSheet.create({ list: { paddingBottom: 30, gap: 10 }, head: { paddingHorizontal: 20, gap: 12 }, search: { height: 50, borderWidth: 1, borderColor: palette.line, borderRadius: 15, flexDirection: "row", alignItems: "center", paddingHorizontal: 13, gap: 8 }, input: { flex: 1, color: palette.ink }, product: { marginHorizontal: 20, flexDirection: "row", gap: 11, alignItems: "center", padding: 12 }, image: { height: 61, width: 61, borderRadius: 16, overflow: "hidden", alignItems: "center", justifyContent: "center", backgroundColor: palette.lavender }, imageFill: { width: "100%", height: "100%" }, store: { color: palette.purple, fontSize: 9, fontWeight: "900" }, name: { color: palette.ink, fontSize: 14, fontWeight: "900", marginTop: 2 }, detail: { color: palette.muted, fontSize: 11, marginTop: 3 } });
