import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function SuperAdminDashboard() { return <RequireRole role="super_admin"><Dashboard /></RequireRole>; }
function Dashboard() { const { session } = usePhaseSession(); const overview = trpc.phase1.superDashboard.useQuery({ sessionToken: session!.token }); if (overview.isLoading) return <LoadingCare />; if (overview.error) return <Page><Text>{overview.error.message}</Text></Page>; const data = overview.data!; return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title="Maamulaha Sare" subtitle="Maaree dukaamada, macaamiisha, alaabta iyo dalabyada" /><View style={styles.hero}><Text style={styles.eyebrow}>WAJIGA 4</Text><Text style={styles.heroTitle}>Ku soo dhawoow, {session!.account.fullName}</Text><Text style={styles.heroText}>Waxaad ansixin kartaa dukaamada, arki kartaa alaabta iyo dalabyada dukaamada, adigoon beddelin dalabka.</Text></View><View style={styles.grid}><Stat icon="hourglass-top" label="Sugaya" value={data.pendingStores} tone="#FFF2D8" /><Stat icon="storefront" label="Firfircoon" value={data.activeStores} tone="#EAF8EF" /><Stat icon="block" label="La hakiyey" value={data.suspendedStores} tone="#FDECEF" /><Stat icon="people" label="Macaamiil" value={data.customerCount} tone={palette.blue} /></View><PrimaryButton label="Maaree dukaamada" icon="storefront" onPress={() => router.push("/super-admin-stores" as never)} /><SecondaryButton label="Warbixinta lacagaha" icon="assessment" onPress={() => router.push("/super-admin-payments" as never)} /><SecondaryButton label="Xisaabta Iftiin" icon="account-balance-wallet" onPress={() => router.push("/super-admin-payment-settings" as never)} /><SecondaryButton label="Eeg dhammaan alaabta" icon="inventory-2" onPress={() => router.push("/super-admin-products" as never)} /><SecondaryButton label="Eeg dhammaan dalabyada" icon="receipt-long" onPress={() => router.push("/super-admin-orders" as never)} /><SecondaryButton label="Eeg macaamiisha" icon="people" onPress={() => router.push("/super-admin-customers" as never)} /><SecondaryButton label="Qoraalkayga" icon="person" onPress={() => router.push("/account-profile" as never)} /></ScrollView></Page>; }
function Stat({ icon, label, value, tone }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; value: number; tone: string }) { return <Card style={[styles.stat, { backgroundColor: tone }]}><MaterialIcons name={icon} size={21} color={palette.purple} /><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></Card>; }
const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 30 }, hero: { padding: 20, borderRadius: 25, backgroundColor: palette.lavender, gap: 6 }, eyebrow: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, heroTitle: { color: palette.ink, fontSize: 22, fontWeight: "900" }, heroText: { color: palette.muted, fontSize: 13, lineHeight: 19 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, stat: { width: "47%", gap: 3 }, value: { color: palette.ink, fontSize: 24, fontWeight: "900" }, label: { color: palette.muted, fontSize: 12, fontWeight: "800" } });
