import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { RequireRole, usePhaseSession } from "@/lib/phase1-session";
import { trpc } from "@/lib/trpc";

export default function SuperAdminStores() { return <RequireRole role="super_admin"><Stores /></RequireRole>; }
function Stores() { const { session } = usePhaseSession(); const stores = trpc.phase1.listStores.useQuery({ sessionToken: session!.token }); const update = trpc.phase1.setStoreStatus.useMutation({ onSuccess: () => stores.refetch() }); if (stores.isLoading) return <LoadingCare />; const change = (id: number, status: "active" | "suspended") => Alert.alert(status === "active" ? "Ansixi dukaan" : "Hakin dukaan", status === "active" ? "Dukaankan ma ansixinaysaa?" : "Dukaankan ma hakinaysaa?", [{ text: "Jooji", style: "cancel" }, { text: status === "active" ? "Ansixi" : "Hakin", style: status === "suspended" ? "destructive" : "default", onPress: () => update.mutate({ sessionToken: session!.token, storeId: id, status }) }]); return <Page><ScrollView contentContainerStyle={styles.scroll}><Header title="Dukaamada" subtitle="Ansixinta iyo hakinta" back={() => router.back()} />{stores.data?.length ? stores.data.map((store) => <Card key={store.id} style={styles.card}><View style={styles.head}><View style={styles.icon}><MaterialIcons name="storefront" size={21} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.name}>{store.storeName}</Text><Text style={styles.owner}>{store.fullName}</Text></View><Status status={store.status} /></View><Text style={styles.detail}>Email: {store.email}</Text><Text style={styles.detail}>Taleefan: {store.phoneNumber}</Text><Text style={styles.detail}>Goobta: {store.location}</Text><Text style={styles.detail}>Magaca isticmaalaha: {store.username}</Text>{store.status !== "active" ? <PrimaryButton label="Ansixi dukaanka" icon="check-circle" onPress={() => change(store.id, "active")} /> : null}{store.status !== "suspended" ? <SecondaryButton label="Hakin dukaanka" icon="block" onPress={() => change(store.id, "suspended")} /> : <SecondaryButton label="Dib u ansixi dukaanka" icon="restore" onPress={() => change(store.id, "active")} />}</Card>) : <Card><Text style={styles.empty}>Weli ma jiro codsi dukaan.</Text></Card>}</ScrollView></Page>; }
function Status({ status }: { status: string }) { const title = status === "pending" ? "Sugaya" : status === "active" ? "Firfircoon" : status === "restricted" ? "RESTRICTED · Commission" : "La hakiyey"; const color = status === "pending" ? palette.warning : status === "active" ? palette.success : status === "restricted" ? palette.warning : palette.danger; const backgroundColor = status === "pending" || status === "restricted" ? "#FFF2D8" : status === "active" ? "#EAF8EF" : "#FDECEF"; return <View style={[styles.status, { backgroundColor }]}><Text style={[styles.statusText, { color }]}>{title}</Text></View>; }
const styles = StyleSheet.create({ scroll: { gap: 13, paddingBottom: 30 }, card: { gap: 10 }, head: { flexDirection: "row", gap: 10, alignItems: "center" }, icon: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: palette.lavender }, name: { color: palette.ink, fontSize: 16, fontWeight: "900" }, owner: { color: palette.muted, fontSize: 12, marginTop: 2 }, status: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10 }, statusText: { fontSize: 10, fontWeight: "900" }, detail: { color: palette.muted, fontSize: 12, lineHeight: 18 }, empty: { color: palette.muted, textAlign: "center", padding: 10 } });
