import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type CartItem = { productId: number; storeAdminId: number; storeName: string | null; name: string; brand: string; imageUrl: string | null; originalPrice: number; finalPrice: number; stock: number; quantity: number; deliveryEnabled: boolean; deliveryFee: number; deliveryAreas: string };
type CartValue = { ready: boolean; items: CartItem[]; deliveryArea: string | null; add: (item: Omit<CartItem, "quantity">) => { accepted: boolean; reason?: string }; changeQuantity: (productId: number, quantity: number) => void; remove: (productId: number) => void; setDeliveryArea: (area: string | null) => void; clear: () => void; };
const CART_KEY = "iftiin-phase3-cart";
const CartContext = createContext<CartValue | null>(null);
export function CartProvider({ children }: { children: React.ReactNode }) { const [ready, setReady] = useState(false); const [items, setItems] = useState<CartItem[]>([]); const [deliveryArea, setDeliveryArea] = useState<string | null>(null); useEffect(() => { AsyncStorage.getItem(CART_KEY).then((raw) => { if (raw) { const saved = JSON.parse(raw) as { items?: CartItem[]; deliveryArea?: string | null }; setItems(saved.items ?? []); setDeliveryArea(saved.deliveryArea ?? null); } }).catch(() => undefined).finally(() => setReady(true)); }, []); useEffect(() => { if (ready) AsyncStorage.setItem(CART_KEY, JSON.stringify({ items, deliveryArea })).catch(() => undefined); }, [ready, items, deliveryArea]); const add = useCallback((item: Omit<CartItem, "quantity">) => { if (items.length && items[0].storeAdminId !== item.storeAdminId) return { accepted: false, reason: "Cart-ku hal dukaan oo keliya ayuu qaadan karaa. Marka hore ka saar alaabta hadda ku jirta." }; setItems((current) => { const existing = current.find((line) => line.productId === item.productId); if (existing) return current.map((line) => line.productId === item.productId ? { ...line, quantity: Math.min(line.stock, line.quantity + 1) } : line); return [...current, { ...item, quantity: 1 }]; }); return { accepted: true }; }, [items]); const changeQuantity = useCallback((productId: number, quantity: number) => setItems((current) => current.flatMap((item) => quantity <= 0 ? (item.productId === productId ? [] : [item]) : (item.productId === productId ? [{ ...item, quantity: Math.min(item.stock, quantity) }] : [item]))), []); const remove = useCallback((productId: number) => setItems((current) => current.filter((item) => item.productId !== productId)), []); const clear = useCallback(() => { setItems([]); setDeliveryArea(null); }, []); const value = useMemo(() => ({ ready, items, deliveryArea, add, changeQuantity, remove, setDeliveryArea, clear }), [ready, items, deliveryArea, add, changeQuantity, remove, clear]); return <CartContext.Provider value={value}>{children}</CartContext.Provider>; }
export function useCart() { const value = useContext(CartContext); if (!value) throw new Error("useCart must be used within CartProvider"); return value; }
