import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, Header, LoadingCare, Page, palette, PrimaryButton, ProgressLine } from "@/components/iftiin-ui";
import { useCare } from "@/lib/skin-care-context";

export default function HomeScreen() {
  const { hydrated, assessment, progress, toggleDailyItem } = useCare();
  if (!hydrated) return <LoadingCare />;
  if (!assessment) return <Welcome />;
  const day = Math.min(28, progress.completedDays.length + 1);
  const morningDone = Boolean(progress.dailyItems["morning-cleanser"] && progress.dailyItems["morning-spf"]);
  const nightDone = Boolean(progress.dailyItems["night-cleanser"] && progress.dailyItems["night-moisturizer"]);
  return <Page><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><Header title="Ku soo dhawoow Iftiin" subtitle="Hagaha daryeelka maqaarkaaga" /><View style={styles.greeting}><View style={styles.greetingBadge}><MaterialIcons name="auto-awesome" size={22} color={palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.eyebrow}>MAQAARKAYGA</Text><Text style={styles.greetingTitle}>{assessment.profile.skinType}</Text><Text style={styles.greetingText}>{assessment.profile.concerns.join(" · ")}</Text></View></View><Card style={styles.todayCard}><View style={styles.todayTop}><View><Text style={styles.eyebrow}>MAANTA</Text><Text style={styles.todayTitle}>Maalinta {day} ee qorshahaaga</Text></View><View style={styles.dayChip}><Text style={styles.dayChipText}>{progress.completedDays.length}/28</Text></View></View><ProgressLine value={(progress.completedDays.length / 28) * 100} /><Text style={styles.todayHint}>Ku soco talaabo yar yar oo joogto ah.</Text></Card><Text style={styles.sectionTitle}>Daryeelka maanta</Text><RoutineRow icon="wb-sunny" label="Subax" detail={morningDone ? "Waa la dhammeeyay" : "Nadiifiye · kareemka qorraxda"} done={morningDone} onPress={() => { toggleDailyItem("morning-cleanser"); toggleDailyItem("morning-spf"); }} /><RoutineRow icon="dark-mode" label="Habeen" detail={nightDone ? "Waa la dhammeeyay" : "Nadiifiye · kareem qoyaansiin"} done={nightDone} onPress={() => { toggleDailyItem("night-cleanser"); toggleDailyItem("night-moisturizer"); }} /><Text style={styles.sectionTitle}>Waxqabadyo degdeg ah</Text><View style={styles.actionGrid}><QuickAction icon="photo-camera" label="Baadhista wejiga" onPress={() => router.navigate("/(tabs)/scan" as never)} /><QuickAction icon="document-scanner" label="Baadhista alaabta" onPress={() => router.push("/product-scanner" as never)} /><QuickAction icon="spa" label="Daryeelka" onPress={() => router.navigate("/(tabs)/routine" as never)} /><QuickAction icon="shopping-bag" label="Alaabo" onPress={() => router.navigate("/(tabs)/products" as never)} /><QuickAction icon="calendar-month" label="28 maalmood" onPress={() => router.push("/plan" as never)} /><QuickAction icon="insights" label="Horumarka" onPress={() => router.push("/progress" as never)} /><QuickAction icon="menu-book" label="Barasho" onPress={() => router.navigate("/(tabs)/learn" as never)} /></View><Card style={styles.safety}><MaterialIcons name="health-and-safety" size={18} color={palette.purple} /><Text style={styles.safetyText}>Natiijooyinkani waa qiimeyn guud oo daryeel maqaarka ah, mana aha baaritaan caafimaad.</Text></Card></ScrollView></Page>;
}

function Welcome() {
  return <Page><ScrollView contentContainerStyle={styles.welcome} showsVerticalScrollIndicator={false}><View style={styles.sunCircle}><View style={styles.faceArc}><MaterialIcons name="face-3" size={70} color={palette.purple} /></View><View style={styles.smallSun}><MaterialIcons name="wb-sunny" size={21} color="#FFFFFF" /></View></View><View><Text style={styles.welcomeBrand}>IFTIIN SKIN CARE</Text><Text style={styles.welcomeTitle}>Baro maqaarkaaga, daryeel si gaar ah loogu diyaariyey adiga.</Text><Text style={styles.welcomeCopy}>Marka hore sawir wejigaaga qaado. Kadib waxaan ku weydiin doonaa toddoba su’aalood si aan u fahanno maqaarkaaga.</Text></View><View style={styles.welcomeNote}><MaterialIcons name="lock-outline" size={18} color={palette.purple} /><Text style={styles.welcomeNoteText}>Sawirkaaga waxaa loo hayaa si gaar ah qalabkaaga.</Text></View><PrimaryButton label="Bilow sawirka wejiga" icon="photo-camera" onPress={() => router.navigate("/(tabs)/scan" as never)} /><Text style={styles.footerText}>Daryeel guud, adigoon isku sheegin dhakhtar.</Text></ScrollView></Page>;
}

function RoutineRow({ icon, label, detail, done, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; detail: string; done: boolean; onPress: () => void }) {
  return <Card style={styles.routineRow}><View style={[styles.routineIcon, done && { backgroundColor: "#E5F5EB" }]}><MaterialIcons name={done ? "check" : icon} size={20} color={done ? palette.success : palette.purple} /></View><View style={{ flex: 1 }}><Text style={styles.routineTitle}>{label}</Text><Text style={styles.routineDetail}>{detail}</Text></View><Pressable onPress={onPress} style={({ pressed }) => [styles.smallAction, done && styles.smallActionDone, pressed && { opacity: 0.78 }]}><Text style={[styles.smallActionText, done && { color: palette.success }]}>{done ? "Waa la sameeyay" : "Samee"}</Text></Pressable></Card>;
}

function QuickAction({ icon, label, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; onPress: () => void }) {
  return <Pressable onPress={onPress} accessibilityRole="button" style={({ pressed }) => [styles.quickAction, pressed && { opacity: 0.72 }]}><View style={styles.quickIcon}><MaterialIcons name={icon} size={22} color={palette.purple} /></View><Text style={styles.quickLabel}>{label}</Text></Pressable>;
}

const styles = StyleSheet.create({
  scroll: { paddingBottom: 30, gap: 14 },
  greeting: { backgroundColor: palette.lavender, borderRadius: 25, padding: 18, flexDirection: "row", alignItems: "center", gap: 13 },
  greetingBadge: { height: 50, width: 50, borderRadius: 18, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  eyebrow: { color: palette.purple, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, greetingTitle: { color: palette.ink, fontSize: 21, fontWeight: "800", marginTop: 2 }, greetingText: { color: palette.muted, fontSize: 12, marginTop: 3 },
  todayCard: { gap: 11 }, todayTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, todayTitle: { color: palette.ink, fontSize: 17, fontWeight: "800", marginTop: 3 }, dayChip: { paddingHorizontal: 11, paddingVertical: 7, backgroundColor: palette.lavender, borderRadius: 12 }, dayChipText: { fontWeight: "800", color: palette.purple, fontSize: 12 }, todayHint: { color: palette.muted, fontSize: 12 },
  sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: "800", marginTop: 8 }, routineRow: { padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, routineIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: palette.lavender }, routineTitle: { color: palette.ink, fontSize: 15, fontWeight: "800" }, routineDetail: { color: palette.muted, fontSize: 12, marginTop: 2 }, smallAction: { backgroundColor: palette.lavender, borderRadius: 12, paddingVertical: 9, paddingHorizontal: 10 }, smallActionDone: { backgroundColor: "#E5F5EB" }, smallActionText: { color: palette.purple, fontSize: 11, fontWeight: "900" },
  actionGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 11 }, quickAction: { width: "47%", backgroundColor: "#F9F8FE", borderWidth: 1, borderColor: palette.line, padding: 13, borderRadius: 19 }, quickIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: palette.lavender, justifyContent: "center", alignItems: "center", marginBottom: 9 }, quickLabel: { color: palette.ink, fontSize: 13, fontWeight: "800" }, safety: { flexDirection: "row", gap: 9, alignItems: "flex-start", backgroundColor: "#FAF9FF" }, safetyText: { color: palette.muted, fontSize: 12, lineHeight: 18, flex: 1 },
  welcome: { flexGrow: 1, justifyContent: "center", gap: 26, paddingVertical: 28 }, sunCircle: { alignSelf: "center", width: 176, height: 176, borderRadius: 88, backgroundColor: palette.lavender, alignItems: "center", justifyContent: "center" }, faceArc: { width: 128, height: 128, borderRadius: 64, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, smallSun: { position: "absolute", right: 17, top: 21, width: 39, height: 39, borderRadius: 19.5, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" }, welcomeBrand: { color: palette.purple, letterSpacing: 2, fontSize: 11, fontWeight: "900", marginBottom: 8 }, welcomeTitle: { color: palette.ink, fontSize: 31, lineHeight: 39, fontWeight: "900", letterSpacing: -0.5 }, welcomeCopy: { color: palette.muted, fontSize: 15, lineHeight: 23, marginTop: 14 }, welcomeNote: { backgroundColor: palette.blue, borderRadius: 16, padding: 14, flexDirection: "row", gap: 8, alignItems: "center" }, welcomeNoteText: { color: palette.ink, fontSize: 12, flex: 1, lineHeight: 17 }, footerText: { color: palette.muted, fontSize: 12, textAlign: "center" },
});
