import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { Card, Header, Page, palette, PrimaryButton } from "@/components/iftiin-ui";
import { catalogGroups, productsForNeed, type SkinNeed } from "@/lib/product-catalog";

const categoryNames = { Cleanser: "Nadiifiyaha", Moisturizer: "Kareemka qoyaansiinta", Sunscreen: "Kareemka qorraxda", Serum: "Dareeraha wejiga" } as const;

export default function ProductsScreen() {
  const [need, setNeed] = useState<SkinNeed>("qallalan");
  const selected = catalogGroups.find((group) => group.id === need)!;
  const products = productsForNeed(need);
  return <Page><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Header title="Alaabta" subtitle="Doorashooyin badan oo baahida maqaarkaaga ku xiran" /><Text style={styles.intro}>Qayb kasta waxay kuu soo bandhigaysaa siddeed alaab oo sawir iyo xog buuxda leh. Magacyada iyo maaddooyinka ka hubi baakadka ka hor isticmaalka.</Text><PrimaryButton label="Fur baadhaha alaabta" icon="document-scanner" onPress={() => router.push("/product-scanner" as never)} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.groupRow}>{catalogGroups.map((group) => <Pressable key={group.id} onPress={() => setNeed(group.id)} style={({ pressed }) => [styles.groupChip, need === group.id && styles.groupChipActive, pressed && { opacity: 0.75 }]}><Text style={[styles.groupChipText, need === group.id && styles.groupChipTextActive]}>{group.title}</Text></Pressable>)}</ScrollView><View style={styles.groupInfo}><View><Text style={styles.groupTitle}>{selected.title}</Text><Text style={styles.groupDescription}>{selected.description}</Text></View><View style={styles.count}><Text style={styles.countText}>{products.length}</Text></View></View>{products.map((product) => <Card key={product.id} style={styles.card}><Image source={product.image} style={styles.image} /><View style={styles.details}><Text style={styles.category}>{categoryNames[product.category]}</Text><Text style={styles.name}>{product.name}</Text><Text style={styles.brand}>{product.brand}</Text><Field label="Maaddooyinka" value={product.ingredients} /><Field label="Noocyada maqaarka" value={product.skinTypes.join(" · ")} /><Field label="Waxa ay ku habboon tahay" value={product.skinConcerns.join(" · ")} /><Field label="Sida loo isticmaalo" value={product.howToUse} /><View style={styles.warning}><MaterialIcons name="info-outline" size={15} color="#9D6B14" /><Text style={styles.warningText}>{product.warnings}</Text></View><Field label="Qiimaha" value={product.price} /><Field label="Helitaanka" value={product.availability} /></View></Card>)}</ScrollView></Page>;
}

function Field({ label, value }: { label: string; value: string }) { return <Text style={styles.field}><Text style={styles.fieldLabel}>{label}: </Text>{value}</Text>; }

const styles = StyleSheet.create({ scroll: { gap: 13, paddingBottom: 30 }, intro: { color: palette.muted, fontSize: 13, lineHeight: 20 }, groupRow: { gap: 8, paddingVertical: 2 }, groupChip: { paddingVertical: 10, paddingHorizontal: 13, borderRadius: 15, backgroundColor: "#F6F5FC", borderWidth: 1, borderColor: palette.line }, groupChipActive: { backgroundColor: palette.purple, borderColor: palette.purple }, groupChipText: { color: palette.ink, fontSize: 12, fontWeight: "800" }, groupChipTextActive: { color: "#FFFFFF" }, groupInfo: { flexDirection: "row", backgroundColor: palette.lavender, padding: 15, borderRadius: 19, alignItems: "center", gap: 10 }, groupTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" }, groupDescription: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3, maxWidth: 270 }, count: { width: 34, height: 34, borderRadius: 12, backgroundColor: "#FFFFFF", justifyContent: "center", alignItems: "center" }, countText: { color: palette.purple, fontSize: 15, fontWeight: "900" }, card: { padding: 0, overflow: "hidden" }, image: { height: 235, width: "100%", resizeMode: "contain", backgroundColor: "#F8F9FC" }, details: { padding: 15, gap: 7 }, category: { color: palette.purple, fontWeight: "900", fontSize: 10, letterSpacing: 1 }, name: { color: palette.ink, fontWeight: "900", fontSize: 18 }, brand: { color: palette.muted, fontSize: 12, marginTop: -4 }, field: { color: palette.muted, fontSize: 12, lineHeight: 18 }, fieldLabel: { color: palette.ink, fontWeight: "900" }, warning: { flexDirection: "row", gap: 6, backgroundColor: "#FFF6E7", borderRadius: 10, padding: 9, alignItems: "flex-start" }, warningText: { color: "#7C5A1D", fontSize: 11, flex: 1, lineHeight: 16 } });
