import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { useCare } from "@/lib/skin-care-context";

export default function ProfileScreen() {
  const { hydrated, assessment, history, deleteCareData } = useCare();
  if (!hydrated) return <LoadingCare />;
  if (!assessment) return <Page><EmptyState icon="person-outline" title="Qoraalkaaga diyaar ma aha" detail="Marka hore samee sawirka wejiga, ka dibna halkan ayaad ka maamuli kartaa xogtaada." action={<PrimaryButton label="Bilow sawirka wejiga" onPress={() => router.navigate("/(tabs)/scan" as never)} />} /></Page>;
  const remove = () => Alert.alert("Tirtir xogta?", "Sawirkaaga, falanqayntaada, iyo horumarkaaga qalabkan ayaa la tirtirayaa.", [{ text: "Jooji", style: "cancel" }, { text: "Tirtir", style: "destructive", onPress: () => deleteCareData() }]);
  return <Page><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Header title="Aniga" subtitle="Xogtaada iyo asturnaanta" /><Card style={styles.profileTop}><View style={styles.avatar}><MaterialIcons name="person" size={30} color={palette.purple} /></View><View><Text style={styles.name}>Qoraalkaaga</Text><Text style={styles.caption}>Xogtaadu waxay ku jirtaa qalabkaaga</Text></View></Card><Text style={styles.label}>TAARIIKHDA SAWIRRADA</Text><Card><Text style={styles.historyTitle}>{history.length} sawir ayaa qalabkan ku keydsan</Text><Text style={styles.historyDetail}>Sawirkii ugu dambeeyay: {new Date(assessment.createdAt).toLocaleDateString()}</Text></Card><Text style={styles.label}>ASTURNAANTA</Text><Card style={styles.privacy}><MaterialIcons name="lock-outline" size={20} color={palette.purple} /><Text style={styles.privacyText}>Sawirkaaga lama wadaago, looma isticmaalo tababar, mana baxo qalabkaaga release-kan. Waxaad tirtiri kartaa wakhti kasta.</Text></Card><Card style={styles.safety}><MaterialIcons name="medical-information" size={20} color="#9D6B14" /><Text style={styles.safetyText}>Haddii aad leedahay xanuun, barar, gubasho ama calaamado daran oo joogto ah, la xiriir dhakhtar maqaarka ku takhasusay.</Text></Card><SecondaryButton label="Tirtir sawirka iyo xogtayda" icon="delete-outline" onPress={remove} /><Text style={styles.account}>Gelitaan iyo kaydinta sawirrada meel dhexe waxaa loo diyaarinayaa in si ammaan ah loo daro mustaqbalka.</Text></ScrollView></Page>;
}

const styles = StyleSheet.create({ scroll: { gap: 13, paddingBottom: 30 }, profileTop: { flexDirection: "row", alignItems: "center", gap: 12 }, avatar: { width: 58, height: 58, borderRadius: 20, justifyContent: "center", alignItems: "center", backgroundColor: palette.lavender }, name: { color: palette.ink, fontSize: 18, fontWeight: "900" }, caption: { color: palette.muted, fontSize: 11, marginTop: 4 }, label: { color: palette.purple, fontWeight: "900", fontSize: 10, letterSpacing: 1.1, marginTop: 8 }, historyTitle: { color: palette.ink, fontWeight: "800", fontSize: 14 }, historyDetail: { color: palette.muted, fontSize: 12, marginTop: 6 }, privacy: { flexDirection: "row", gap: 9, backgroundColor: palette.blue }, privacyText: { color: palette.ink, fontSize: 12, lineHeight: 18, flex: 1 }, safety: { flexDirection: "row", gap: 9, backgroundColor: "#FFF6E7" }, safetyText: { color: "#6F521D", fontSize: 12, lineHeight: 18, flex: 1 }, account: { color: palette.muted, fontSize: 11, lineHeight: 17, textAlign: "center", paddingHorizontal: 15 } });
