import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, Header, LoadingCare, Page, palette, PrimaryButton, SecondaryButton } from "@/components/iftiin-ui";
import { productsForRoutine, type CatalogProduct } from "@/lib/product-catalog";
import { useCare } from "@/lib/skin-care-context";

export default function RoutineScreen() {
  const { hydrated, assessment } = useCare();
  if (!hydrated) return <LoadingCare />;
  if (!assessment) return <Page><EmptyState icon="spa" title="Daryeelkaaga halkan ayuu imanayaa" detail="Marka hore samee sawirka wejiga si aan kuu diyaarinno talaabooyin ku habboon." action={<PrimaryButton label="Bilow sawirka wejiga" onPress={() => router.navigate("/(tabs)/scan" as never)} />} /></Page>;
  const suggestions = productsForRoutine(assessment.profile.concerns);
  const cleanser = suggestions.find((item) => item.category === "Cleanser");
  const moisturizer = suggestions.find((item) => item.category === "Moisturizer");
  const sunscreen = suggestions.find((item) => item.category === "Sunscreen");
  const treatment = suggestions.find((item) => item.category === "Serum");
  return <Page><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Header title="Daryeelkaaga gaarka ah" subtitle={`${assessment.profile.routineStyle} · ${assessment.profile.skinType}`} /><Text style={styles.intro}>Waxaan kuu soo xulnay talaabooyin yar yar iyo alaabta ku jirta liiska. Ku bilow tartiib, alaab cusubna ku tijaabi meel yar oo maqaarka ah.</Text><RoutineBlock icon="wb-sunny" title="SUBAX" subtitle="Ilaali difaaca maqaarka" products={[cleanser, moisturizer, sunscreen].filter(Boolean) as CatalogProduct[]} /><RoutineBlock icon="dark-mode" title="HABEEN" subtitle="Nadiifi oo xooji" products={[cleanser, treatment ?? moisturizer, moisturizer].filter(Boolean) as CatalogProduct[]} /><Card style={styles.mini}><MaterialIcons name="tips-and-updates" size={20} color={palette.purple} /><Text style={styles.miniText}>Ha ku darin alaabo badan hal mar. Mid cusub hal mar uun tijaabi si aad ula socoto falcelinta maqaarka.</Text></Card><PrimaryButton label="Fur baadhaha alaabta" icon="document-scanner" onPress={() => router.push("/product-scanner" as never)} /><SecondaryButton label="Fur qorshaha 28 maalmood" icon="calendar-month" onPress={() => router.push("/plan" as never)} /><SecondaryButton label="Eeg liiska alaabta" icon="shopping-bag" onPress={() => router.navigate("/(tabs)/products" as never)} /></ScrollView></Page>;
}

function RoutineBlock({ icon, title, subtitle, products }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; subtitle: string; products: CatalogProduct[] }) { return <Card style={styles.block}><View style={styles.blockHead}><View style={styles.icon}><MaterialIcons name={icon} size={19} color={palette.purple} /></View><View><Text style={styles.blockTitle}>{title}</Text><Text style={styles.blockSub}>{subtitle}</Text></View></View>{products.map((product, index) => <View key={`${product.id}-${index}`} style={styles.step}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><Image source={product.image} style={styles.productImage} /><View style={{ flex: 1 }}><Text style={styles.stepText}>{product.name}</Text><Text style={styles.productBrand}>{product.brand}</Text></View></View>)}</Card>; }

const styles = StyleSheet.create({ scroll: { gap: 15, paddingBottom: 30 }, intro: { color: palette.muted, lineHeight: 21, fontSize: 14 }, block: { gap: 13 }, blockHead: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 1 }, icon: { width: 37, height: 37, borderRadius: 13, backgroundColor: palette.lavender, justifyContent: "center", alignItems: "center" }, blockTitle: { color: palette.ink, fontWeight: "900", fontSize: 14, letterSpacing: 1 }, blockSub: { color: palette.muted, fontSize: 12, marginTop: 2 }, step: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 4 }, number: { width: 25, height: 25, borderRadius: 12.5, alignItems: "center", justifyContent: "center", backgroundColor: palette.blue }, numberText: { color: palette.purple, fontSize: 12, fontWeight: "900" }, productImage: { width: 42, height: 42, borderRadius: 12, resizeMode: "contain", backgroundColor: "#F7F8FC" }, stepText: { color: palette.ink, fontWeight: "800", fontSize: 13, flex: 1 }, productBrand: { color: palette.muted, fontSize: 10, marginTop: 2 }, mini: { flexDirection: "row", gap: 10, backgroundColor: palette.blue }, miniText: { color: palette.ink, fontSize: 12, lineHeight: 18, flex: 1 } });
